// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {bridge} from '../models';
import {engine} from '../models';
import {gitrepo} from '../models';
import {storage} from '../models';
import {plane} from '../models';
import {taskspace} from '../models';
import {execution} from '../models';
import {report} from '../models';

export function AbortAgentRun(arg1:agent.AbortRequest):Promise<void>;

export function AcceptMemorySuggestion(arg1:any):Promise<Record<string, any>>;

export function AcceptMemorySuggestionForTab(arg1:any,arg2:any):Promise<Record<string, any>>;

export function AcceptSkillSuggestion(arg1:any):Promise<Record<string, any>>;

export function AcceptSkillSuggestionForTab(arg1:any,arg2:any):Promise<Record<string, any>>;

export function ActivateBaseStyle(arg1:any):Promise<Record<string, any>>;

export function ActivateReasonixTask(arg1:string,arg2:string,arg3:string,arg4:number):Promise<bridge.TabView>;

export function ActivateThemePack(arg1:any):Promise<Record<string, any>>;

export function ActivateTopic(arg1:any,arg2:any,arg3:any,arg4:any):Promise<Record<string, any>>;

export function AddMCPServer(arg1:any):Promise<Record<string, any>>;

export function AddOfficialProviderAccess(arg1:any,arg2:any):Promise<Record<string, any>>;

export function AddPermissionRule(arg1:any,arg2:any):Promise<Record<string, any>>;

export function AddProviderPresetAccess(arg1:any,arg2:any):Promise<Record<string, any>>;

export function AddRemoteForward(arg1:any,arg2:any):Promise<Record<string, any>>;

export function AddRemoteHost(arg1:any):Promise<Record<string, any>>;

export function AddSkillPath(arg1:any):Promise<Record<string, any>>;

export function AgentSessionCommand(arg1:agent.CommandRequest):Promise<Record<string, any>>;

export function AnalyzePlaneCandidate(arg1:string,arg2:engine.PISettings):Promise<engine.CandidateAnalysis>;

export function AnalyzeRequirements(arg1:engine.RequirementAnalysisInput,arg2:engine.PISettings):Promise<engine.RequirementAnalysisResult>;

export function AnswerQuestion(arg1:string,arg2:Array<any>):Promise<void>;

export function AnswerQuestionForTab(arg1:string,arg2:string,arg3:Array<any>):Promise<void>;

export function ApplyUpdate():Promise<Record<string, any>>;

export function Approve(arg1:any,arg2:any,arg3:any,arg4:any):Promise<Record<string, any>>;

export function ApproveTab(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function AttachDropped(arg1:any):Promise<Record<string, any>>;

export function AttachmentDataURL(arg1:string):Promise<string>;

export function AuthorizeAndConnectMCPServer(arg1:any):Promise<Record<string, any>>;

export function AutoResearchCurrent():Promise<Record<string, any>>;

export function AutoResearchFindings(arg1:any,arg2:any):Promise<Record<string, any>>;

export function AutoResearchList(arg1:any):Promise<Record<string, any>>;

export function AutoResearchOpenTask(arg1:any):Promise<Record<string, any>>;

export function AutoResearchRecordEvidence(arg1:any,arg2:any,arg3:any):Promise<Record<string, any>>;

export function AutoResearchStatus(arg1:any):Promise<Record<string, any>>;

export function AvailableSubagentTools():Promise<Array<any>>;

export function Balance():Promise<Record<string, any>>;

export function BalanceForTab(arg1:string):Promise<Record<string, any>>;

export function BindGitRepository(arg1:gitrepo.BindRequest):Promise<storage.GitBindingRecord>;

export function BotRuntimeStatus():Promise<Record<string, any>>;

export function Cancel():Promise<void>;

export function CancelForTab(arg1:string):Promise<void>;

export function CancelTab(arg1:string):Promise<void>;

export function CancelTrySubagentProfile():Promise<void>;

export function Capabilities():Promise<Record<string, any>>;

export function CapabilityDiagnostics(arg1:any):Promise<Record<string, any>>;

export function CheckUpdate(arg1:any):Promise<Record<string, any>>;

export function Checkpoints():Promise<Array<any>>;

export function CheckpointsForTab(arg1:string):Promise<Array<any>>;

export function CleanupTaskGitWorktree(arg1:gitrepo.CleanupRequest):Promise<storage.GitBindingRecord>;

export function ClearBotSecret(arg1:any):Promise<void>;

export function ClearGoal():Promise<void>;

export function ClearGoalForTab(arg1:string):Promise<void>;

export function ClearMCPServerAuthentication(arg1:any):Promise<void>;

export function ClearProviderKey(arg1:string):Promise<void>;

export function ClearSession():Promise<void>;

export function ClearSessionForTab(arg1:string):Promise<void>;

export function ClearState():Promise<void>;

export function CloseMainWindow():Promise<void>;

export function CloseTab(arg1:any):Promise<Record<string, any>>;

export function CloseTerminalForTab(arg1:string,arg2:string):Promise<void>;

export function CollectPlaneWorkItems(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<Array<plane.Candidate>>;

export function Commands():Promise<Array<Record<string, any>>>;

export function CommitTaskGitChanges(arg1:gitrepo.CommitRequest):Promise<gitrepo.CommitResult>;

export function Compact():Promise<Record<string, any>>;

export function CompactForTab(arg1:string):Promise<void>;

export function ConfirmAction(arg1:any):Promise<Record<string, any>>;

export function ConfirmRemoteHostKey(arg1:any,arg2:any):Promise<Record<string, any>>;

export function ConfirmRemoteSecret(arg1:any,arg2:any,arg3:any,arg4:any):Promise<Record<string, any>>;

export function ConnectKey(arg1:any):Promise<void>;

export function ConnectRemoteHost(arg1:any):Promise<void>;

export function ContextPanel(arg1:string):Promise<Record<string, any>>;

export function ContextUsage():Promise<Array<any>>;

export function ContextUsageForTab(arg1:string):Promise<Record<string, any>>;

export function CopyThemePack(arg1:any,arg2:any,arg3:any):Promise<void>;

export function CreateAgentSession(arg1:agent.CreateSessionRequest):Promise<storage.AgentSessionRecord>;

export function CreateDeliveryWorktree(arg1:any):Promise<Record<string, any>>;

export function CreateSubagentProfile(arg1:any):Promise<Record<string, any>>;

export function CreateTerminalForTab(arg1:any,arg2:any,arg3:any):Promise<Record<string, any>>;

export function CreateTopic(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function DeleteDailyReportToken(arg1:string,arg2:string):Promise<void>;

export function DeletePlaneToken(arg1:string,arg2:string):Promise<void>;

export function DeleteProvider(arg1:any):Promise<Record<string, any>>;

export function DeleteRecoveryCopy(arg1:string):Promise<void>;

export function DeleteRemotePath(arg1:any,arg2:any,arg3:any):Promise<Record<string, any>>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSubagentProfile(arg1:any,arg2:any):Promise<Record<string, any>>;

export function DeleteThemePack(arg1:any):Promise<Record<string, any>>;

export function DeleteTopic(arg1:any):Promise<Record<string, any>>;

export function DeliveryWorktreeAvailability(arg1:string):Promise<Record<string, any>>;

export function DesktopStartupSettings():Promise<Record<string, any>>;

export function DiagnoseBotConnection(arg1:any):Promise<void>;

export function DisableThemePack():Promise<Record<string, any>>;

export function DisconnectRemoteHost(arg1:any):Promise<Record<string, any>>;

export function DownloadUpdate(arg1:any):Promise<Record<string, any>>;

export function DownloadUpdateRequest(arg1:any,arg2:any,arg3:any):Promise<Record<string, any>>;

export function Effort():Promise<Record<string, any>>;

export function EffortForTab(arg1:string):Promise<Record<string, any>>;

export function EngineStatuses():Promise<Array<engine.Status>>;

export function EnsureBlankSurface(arg1:string,arg2:string):Promise<bridge.TabView>;

export function EnsureBlankTab(arg1:string,arg2:string):Promise<bridge.TabView>;

export function EnsureRemoteServer(arg1:any,arg2:any):Promise<void>;

export function EnsureTaskWorkspace(arg1:string):Promise<storage.TaskWorkspaceRecord>;

export function ExportThemePack(arg1:any,arg2:any):Promise<void>;

export function ExternalOpeners():Promise<Record<string, any>>;

export function FetchProviderModels(arg1:any):Promise<Record<string, any>>;

export function FollowUpAgent(arg1:agent.PromptRequest):Promise<storage.AgentMessageRecord>;

export function Forget(arg1:string):Promise<void>;

export function ForgetForTab(arg1:string,arg2:string):Promise<void>;

export function Fork(arg1:number):Promise<string>;

export function ForkForTab(arg1:string,arg2:number):Promise<bridge.TabView>;

export function GenerateDailyReport(arg1:engine.DailyReportGenerationInput,arg2:engine.PISettings):Promise<engine.DailyReportGenerationResult>;

export function GetActiveThemePack():Promise<any>;

export function GetAgentHistoryPage(arg1:agent.HistoryPageRequest):Promise<agent.HistoryPage>;

export function GetDesktopZoomFactor():Promise<number>;

export function GetTaskContextRoot():Promise<storage.TaskContextRootInfo>;

export function GetTaskFileDiff(arg1:string,arg2:string):Promise<gitrepo.FileDiffView>;

export function GetTaskGitStatus(arg1:string):Promise<gitrepo.StatusView>;

export function GetThemeExperience():Promise<Record<string, any>>;

export function GitBranches():Promise<Record<string, any>>;

export function GitCheckout(arg1:any):Promise<Record<string, any>>;

export function HasDailyReportToken(arg1:string,arg2:string):Promise<boolean>;

export function HasPlaneToken(arg1:string,arg2:string):Promise<boolean>;

export function HeartbeatGenerateID():Promise<string>;

export function HeartbeatListTasks():Promise<Array<any>>;

export function HeartbeatReloadTasks():Promise<Array<any>>;

export function HeartbeatSaveTasks(arg1:any):Promise<void>;

export function HeartbeatTriggerNow(arg1:string):Promise<void>;

export function History():Promise<Array<bridge.HistoryMessageView>>;

export function HistoryCheckpointTurnsForTab(arg1:string):Promise<Array<number>>;

export function HistoryForTab(arg1:string):Promise<Array<bridge.HistoryMessageView>>;

export function HistoryPage(arg1:number,arg2:number):Promise<bridge.HistoryPageView>;

export function HistoryPageForTab(arg1:string,arg2:number,arg3:number):Promise<bridge.HistoryPageView>;

export function HooksSettings(arg1:any):Promise<void>;

export function ImportAgentAttachments(arg1:agent.ImportAttachmentsRequest):Promise<Array<agent.ResourceDescriptor>>;

export function ImportThemePack(arg1:any,arg2:any):Promise<void>;

export function InstallMCPServer(arg1:any):Promise<Record<string, any>>;

export function InstallPlugin(arg1:any,arg2:any):Promise<Record<string, any>>;

export function InstallUpdate(arg1:any):Promise<Record<string, any>>;

export function InstallUpdateRequest(arg1:any,arg2:any,arg3:any):Promise<Record<string, any>>;

export function IsMainWindowMaximised():Promise<boolean>;

export function Jobs():Promise<Record<string, any>>;

export function JobsForTab(arg1:string):Promise<Array<any>>;

export function LaunchReasonix():Promise<void>;

export function ListAgentArtifacts(arg1:string):Promise<Array<agent.ResourceDescriptor>>;

export function ListAgentMessages(arg1:string,arg2:string):Promise<Array<storage.AgentMessageRecord>>;

export function ListAgentPermissionGrants(arg1:string,arg2:string):Promise<Array<storage.PermissionGrantRecord>>;

export function ListAgentPermissionRequests(arg1:string,arg2:string):Promise<Array<agent.PermissionRequest>>;

export function ListAgentResources(arg1:agent.ResourceSearchRequest):Promise<Array<agent.ResourceDescriptor>>;

export function ListAgentSessions(arg1:string):Promise<Array<storage.AgentSessionRecord>>;

export function ListAgentToolCalls(arg1:string,arg2:string):Promise<Array<storage.ToolCallRecord>>;

export function ListDir(arg1:any):Promise<void>;

export function ListDirForTab(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function ListExecutionRuns(arg1:string,arg2:string):Promise<Array<storage.ExecutionRunRecord>>;

export function ListPlaneProjects(arg1:string,arg2:string):Promise<Array<plane.Project>>;

export function ListProjectTree():Promise<Array<any>>;

export function ListRemoteDir(arg1:any,arg2:any):Promise<void>;

export function ListSessions():Promise<Array<bridge.SessionMetaView>>;

export function ListTabs():Promise<Array<bridge.TabView>>;

export function ListTaskWorkspaceFiles(arg1:string,arg2:string):Promise<Array<taskspace.WorkspaceEntry>>;

export function ListThemePacks():Promise<void>;

export function ListTrashedSessions():Promise<Array<bridge.SessionMetaView>>;

export function ListWorkspaces():Promise<Array<any>>;

export function LoadPlaneWorkItemDetails(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<plane.Candidate>;

export function LoadState():Promise<string>;

export function MCPMarketplace(arg1:any):Promise<void>;

export function MCPMarketplaceResolve(arg1:any):Promise<void>;

export function MCPServers():Promise<void>;

export function Memory():Promise<Record<string, any>>;

export function MemoryForTab(arg1:string):Promise<Record<string, any>>;

export function MemoryRevisions(arg1:string):Promise<Array<any>>;

export function MemoryRevisionsForTab(arg1:string,arg2:string):Promise<Array<any>>;

export function MemorySuggestions():Promise<Array<any>>;

export function MemorySuggestionsForTab(arg1:string):Promise<Array<any>>;

export function Meta():Promise<bridge.MetaView>;

export function MetaForTab(arg1:string):Promise<bridge.MetaView>;

export function MigrateDesktopPreferences(arg1:any,arg2:any,arg3:any):Promise<void>;

export function MinimiseMainWindow():Promise<void>;

export function MkdirRemote(arg1:any,arg2:any):Promise<Record<string, any>>;

export function Models():Promise<Array<bridge.ModelInfoView>>;

export function ModelsForTab(arg1:string):Promise<Array<bridge.ModelInfoView>>;

export function NeedsOnboarding():Promise<boolean>;

export function NewSession():Promise<void>;

export function NewSessionForTab(arg1:string):Promise<void>;

export function OpenAgentArtifact(arg1:string,arg2:string):Promise<void>;

export function OpenChannelSessionForTab(arg1:any,arg2:any):Promise<void>;

export function OpenChannelSessionPageForTab(arg1:any,arg2:any,arg3:any):Promise<void>;

export function OpenDownloadPage():Promise<Record<string, any>>;

export function OpenGlobalTab(arg1:string):Promise<bridge.TabView>;

export function OpenProjectTab(arg1:any,arg2:any):Promise<Record<string, any>>;

export function OpenRemoteWorkspace(arg1:any,arg2:any):Promise<Record<string, any>>;

export function OpenTaskContextRoot():Promise<void>;

export function OpenTopicSession(arg1:any,arg2:any,arg3:any,arg4:any):Promise<Record<string, any>>;

export function OpenWorkspaceInExternalOpener(arg1:any):Promise<Record<string, any>>;

export function OpenWorkspaceInExternalOpenerForTab(arg1:any,arg2:any):Promise<Record<string, any>>;

export function OpenWorkspacePath(arg1:any):Promise<Record<string, any>>;

export function OpenWorkspacePathForTab(arg1:string,arg2:string):Promise<void>;

export function PickExportFile(arg1:any,arg2:any):Promise<string>;

export function PickPluginFolder():Promise<string>;

export function PickSkillFolder():Promise<string>;

export function PickThemeBackground():Promise<string>;

export function PickWorkspace():Promise<void>;

export function PlanPluginInstall(arg1:any,arg2:any):Promise<void>;

export function Platform():Promise<string>;

export function PluginDoctor(arg1:any):Promise<Record<string, any>>;

export function Plugins():Promise<Array<any>>;

export function PollBotConnectionInstall(arg1:string):Promise<Record<string, any>>;

export function PreviewAgentResource(arg1:agent.ResourcePreviewRequest):Promise<taskspace.FilePreview>;

export function PreviewSession(arg1:string):Promise<Array<bridge.HistoryMessageView>>;

export function PurgeRecoveryCopy(arg1:any):Promise<void>;

export function PurgeTrashedSession(arg1:any):Promise<void>;

export function ReadAgentToolOutput(arg1:agent.ToolOutputRequest):Promise<agent.ToolOutput>;

export function ReadFile(arg1:any):Promise<Record<string, any>>;

export function ReadFileForTab(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ReadRemoteFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ReadTaskWorkspaceFile(arg1:string,arg2:string):Promise<taskspace.FilePreview>;

export function ReasonixCloseTab(arg1:string):Promise<void>;

export function ReasonixEnsureTab(arg1:string,arg2:string,arg3:string):Promise<bridge.TabView>;

export function ReasonixHomeInfo():Promise<Record<string, any>>;

export function ReasonixProviders():Promise<Array<bridge.ProviderSettingView>>;

export function ReasonixRemoveProvider(arg1:string):Promise<void>;

export function ReasonixSaveProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ReasonixSetApprovalMode(arg1:string):Promise<void>;

export function ReasonixSetDefaultModel(arg1:string):Promise<void>;

export function ReasonixSetHomeIsolated(arg1:boolean):Promise<void>;

export function ReasonixSetPlannerModel(arg1:string):Promise<void>;

export function ReasonixSettings():Promise<bridge.SettingsView>;

export function ReasonixTestProvider(arg1:string):Promise<Record<string, any>>;

export function ReconnectMCPServer(arg1:any):Promise<Record<string, any>>;

export function RecoverTaskGitWorktree(arg1:gitrepo.RecoverRequest):Promise<storage.GitBindingRecord>;

export function RecoveryCheckpointEnabled():Promise<boolean>;

export function RecoveryCheckpointEnabledTab(arg1:any):Promise<Record<string, any>>;

export function RefreshSkills():Promise<void>;

export function ReloadCommands():Promise<Record<string, any>>;

export function ReloadSettings():Promise<void>;

export function Remember(arg1:string,arg2:string):Promise<string>;

export function RememberForTab(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RemoteConnectionStatuses():Promise<Array<any>>;

export function RemoteForwards(arg1:any):Promise<Array<any>>;

export function RemoteHosts():Promise<Array<any>>;

export function RemoteLastWorkspace(arg1:any):Promise<Array<any>>;

export function RemoteServerLogs(arg1:any,arg2:any):Promise<Array<any>>;

export function RemoteServerStatus(arg1:any):Promise<Record<string, any>>;

export function RemoveAgentMessageReference(arg1:agent.RemoveReferenceRequest):Promise<void>;

export function RemoveMCPServer(arg1:any):Promise<Record<string, any>>;

export function RemovePermissionRule(arg1:any,arg2:any):Promise<Record<string, any>>;

export function RemovePlugin(arg1:any):Promise<Record<string, any>>;

export function RemoveProviderAccess(arg1:any):Promise<Record<string, any>>;

export function RemoveRemoteForward(arg1:any,arg2:any):Promise<Record<string, any>>;

export function RemoveRemoteHost(arg1:any):Promise<Record<string, any>>;

export function RemoveSkillPath(arg1:any):Promise<Record<string, any>>;

export function RemoveWorkspace(arg1:any):Promise<Record<string, any>>;

export function RenameProject(arg1:string,arg2:string):Promise<void>;

export function RenameRemotePath(arg1:any,arg2:any,arg3:any):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RenameTerminalForTab(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameTopic(arg1:string,arg2:string):Promise<void>;

export function ReorderProjects(arg1:Array<string>):Promise<void>;

export function ReorderTabs(arg1:Array<string>):Promise<void>;

export function ReplayPendingPrompts():Promise<void>;

export function ReportCrash(arg1:string,arg2:string):Promise<void>;

export function ResetProviderPresetAccess(arg1:any):Promise<Record<string, any>>;

export function ResetThemePack():Promise<void>;

export function ResizeTerminalForTab(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function ResolveAgentPermission(arg1:agent.ResolvePermissionRequest):Promise<agent.PermissionRequest>;

export function ResolveRecovery(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResolveRecoveryTab(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RestartApplication():Promise<Record<string, any>>;

export function RestoreArchivedMemory(arg1:string):Promise<void>;

export function RestoreArchivedMemoryForTab(arg1:string,arg2:string):Promise<void>;

export function RestoreGraphiteAppearance():Promise<void>;

export function RestoreMemoryRevision(arg1:string,arg2:string):Promise<void>;

export function RestoreMemoryRevisionForTab(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RestoreSession(arg1:string):Promise<void>;

export function ResumeAgentSession(arg1:agent.SessionRequest):Promise<storage.AgentSessionRecord>;

export function ResumeGoalForTab(arg1:string):Promise<boolean>;

export function ResumeSession(arg1:string):Promise<Array<bridge.HistoryMessageView>>;

export function ResumeSessionForTab(arg1:string,arg2:string):Promise<Array<bridge.HistoryMessageView>>;

export function ResumeSessionPage(arg1:string,arg2:number):Promise<bridge.HistoryPageView>;

export function ResumeSessionPageForTab(arg1:string,arg2:string,arg3:number):Promise<bridge.HistoryPageView>;

export function RevealPath(arg1:any):Promise<void>;

export function RevealWorkspacePath(arg1:any):Promise<void>;

export function RevealWorkspacePathForTab(arg1:any,arg2:any):Promise<void>;

export function RevokeAgentPermissionGrant(arg1:agent.RevokePermissionGrantRequest):Promise<storage.PermissionGrantRecord>;

export function Rewind(arg1:number,arg2:string):Promise<void>;

export function RewindForTab(arg1:string,arg2:number,arg3:string):Promise<void>;

export function RunShell(arg1:any):Promise<Record<string, any>>;

export function RunShellForTab(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SaveClipboardImage():Promise<string>;

export function SaveDailyReportToken(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveDoc(arg1:string,arg2:string):Promise<void>;

export function SaveDocForTab(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveExportFile(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveExportImageFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveHooksSettings(arg1:any,arg2:any):Promise<void>;

export function SaveHooksSettingsForRoot(arg1:any,arg2:any,arg3:any):Promise<void>;

export function SavePastedFile(arg1:string,arg2:string):Promise<string>;

export function SavePastedImage(arg1:string):Promise<string>;

export function SavePlaneToken(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveProvider(arg1:Record<string, any>):Promise<void>;

export function SaveProviderKey(arg1:string,arg2:string):Promise<void>;

export function SaveProviderWithKey(arg1:Record<string, any>,arg2:string):Promise<void>;

export function SaveState(arg1:string):Promise<void>;

export function SaveThemePack(arg1:any):Promise<Record<string, any>>;

export function SaveWindowState(arg1:any):Promise<Record<string, any>>;

export function ScanPromptHistory(arg1:string):Promise<Record<string, any>>;

export function ScanSSHConfig():Promise<void>;

export function SearchFileRefs(arg1:any):Promise<Record<string, any>>;

export function SearchFileRefsForTab(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function SelectDailyReportProjectDirectory():Promise<string>;

export function SelectGitRepository():Promise<string>;

export function SelectTaskContextRoot():Promise<string>;

export function SendAgentPrompt(arg1:agent.PromptRequest):Promise<storage.ExecutionRunRecord>;

export function SetActiveTab(arg1:string):Promise<void>;

export function SetAgentParams(arg1:any,arg2:any,arg3:any,arg4:any):Promise<Record<string, any>>;

export function SetAutoApproveTools(arg1:any):Promise<Record<string, any>>;

export function SetAutoPlan(arg1:any):Promise<Record<string, any>>;

export function SetBotConnectionToolApprovalMode(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetBotSecret(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetBotSettings(arg1:any):Promise<Record<string, any>>;

export function SetBypass(arg1:any):Promise<Record<string, any>>;

export function SetCloseBehavior(arg1:any):Promise<void>;

export function SetColdResumePrune(arg1:any):Promise<Record<string, any>>;

export function SetCollaborationMode(arg1:any):Promise<Record<string, any>>;

export function SetCollaborationModeForTab(arg1:string,arg2:string):Promise<void>;

export function SetComposerProfileForTab(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function SetDefaultAutoRecoveryCheckpoint(arg1:any):Promise<Record<string, any>>;

export function SetDefaultModel(arg1:any):Promise<Record<string, any>>;

export function SetDefaultToolApprovalMode(arg1:any):Promise<Record<string, any>>;

export function SetDesktopAppearance(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetDesktopCheckUpdates(arg1:any):Promise<Record<string, any>>;

export function SetDesktopConversationWidth(arg1:any):Promise<Record<string, any>>;

export function SetDesktopCurrency(arg1:any):Promise<Record<string, any>>;

export function SetDesktopLanguage(arg1:any):Promise<Record<string, any>>;

export function SetDesktopLayoutStyle(arg1:any):Promise<Record<string, any>>;

export function SetDesktopMetrics(arg1:any):Promise<Record<string, any>>;

export function SetDesktopTelemetry(arg1:any):Promise<Record<string, any>>;

export function SetDesktopUpdateChannel(arg1:any):Promise<Record<string, any>>;

export function SetDesktopZoomFactor(arg1:any):Promise<Record<string, any>>;

export function SetDisplayMode(arg1:any):Promise<Record<string, any>>;

export function SetEffort(arg1:any):Promise<Record<string, any>>;

export function SetEffortForTab(arg1:string,arg2:string):Promise<void>;

export function SetExpandThinking(arg1:any):Promise<Record<string, any>>;

export function SetGoal(arg1:any):Promise<Record<string, any>>;

export function SetGoalForTab(arg1:string,arg2:string):Promise<void>;

export function SetMCPServerEnabled(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetMCPServerTier(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetMaxParallelWriters(arg1:any):Promise<Record<string, any>>;

export function SetMaxSubagentConcurrency(arg1:any):Promise<Record<string, any>>;

export function SetMaxSubagentDepth(arg1:any):Promise<Record<string, any>>;

export function SetMode(arg1:any):Promise<Record<string, any>>;

export function SetModeForTab(arg1:string,arg2:string):Promise<Array<string>>;

export function SetModel(arg1:any):Promise<Record<string, any>>;

export function SetModelForTab(arg1:string,arg2:string):Promise<void>;

export function SetNetwork(arg1:any):Promise<Record<string, any>>;

export function SetPermissionMode(arg1:string):Promise<void>;

export function SetPlanMode(arg1:any):Promise<Record<string, any>>;

export function SetPlannerModel(arg1:any):Promise<Record<string, any>>;

export function SetPluginEnabled(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetPreferredExternalOpener(arg1:any):Promise<Record<string, any>>;

export function SetProjectColor(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetProjectPinned(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetProviderKey(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetReasoningLanguage(arg1:any):Promise<Record<string, any>>;

export function SetRecoveryCheckpointEnabled(arg1:any):Promise<Record<string, any>>;

export function SetRecoveryCheckpointEnabledTab(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetSandbox(arg1:any,arg2:any,arg3:any,arg4:any,arg5:any):Promise<Record<string, any>>;

export function SetSkillEnabled(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetStatusBarItems(arg1:any):Promise<Record<string, any>>;

export function SetStatusBarStyle(arg1:any):Promise<Record<string, any>>;

export function SetSubagentEffort(arg1:any):Promise<Record<string, any>>;

export function SetSubagentModel(arg1:any):Promise<Record<string, any>>;

export function SetSubagentProfileEffort(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetSubagentProfileModel(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetTaskContextRoot(arg1:string):Promise<storage.TaskContextRootInfo>;

export function SetTokenMode(arg1:any):Promise<Record<string, any>>;

export function SetTokenModeForTab(arg1:string,arg2:string):Promise<void>;

export function SetToolApprovalMode(arg1:any):Promise<Record<string, any>>;

export function SetToolApprovalModeForTab(arg1:string,arg2:string):Promise<Array<string>>;

export function SetTopicPinned(arg1:any,arg2:any):Promise<Record<string, any>>;

export function SetTrayLocale(arg1:string):Promise<void>;

export function Settings():Promise<Record<string, any>>;

export function SetupPlaneConnection(arg1:string,arg2:string):Promise<plane.ConnectionSetup>;

export function SkillsSettings():Promise<Record<string, any>>;

export function SlashArgs(arg1:string):Promise<Record<string, any>>;

export function StartBotConnectionInstall(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Steer(arg1:any):Promise<Record<string, any>>;

export function SteerAgent(arg1:agent.PromptRequest):Promise<storage.AgentMessageRecord>;

export function SteerForTab(arg1:string,arg2:string):Promise<void>;

export function StopAgentToolExecution(arg1:execution.StopRequest):Promise<void>;

export function StopRemoteServer(arg1:string):Promise<void>;

export function Submit(arg1:string):Promise<void>;

export function SubmitDailyReport(arg1:string,arg2:string,arg3:string,arg4:string):Promise<report.SubmitResult>;

export function SubmitDeliveryRecoveryToTab(arg1:any,arg2:any,arg3:any):Promise<void>;

export function SubmitDisplay(arg1:Record<string, any>,arg2:string):Promise<void>;

export function SubmitDisplayToTab(arg1:any,arg2:any,arg3:any):Promise<void>;

export function SubmitEditedDisplayToTab(arg1:any,arg2:any,arg3:any,arg4:any):Promise<void>;

export function SubmitInitialGoalToTab(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<any>,arg6:string,arg7:string,arg8:string,arg9:number,arg10:number):Promise<Array<string>>;

export function SubmitInvocationsToTab(arg1:any,arg2:any,arg3:any,arg4:any):Promise<void>;

export function SubmitToTab(arg1:string,arg2:string):Promise<void>;

export function SummarizeFrom(arg1:number):Promise<void>;

export function SummarizeFromForTab(arg1:string,arg2:number):Promise<void>;

export function SummarizeUpTo(arg1:number):Promise<void>;

export function SummarizeUpToForTab(arg1:string,arg2:number):Promise<void>;

export function SwitchWorkspace(arg1:any):Promise<void>;

export function TerminalOutputForTab(arg1:string,arg2:string):Promise<Record<string, any>>;

export function TerminalWorkspaceForTab(arg1:string):Promise<Record<string, any>>;

export function TestBotConnection(arg1:any,arg2:any):Promise<void>;

export function TestPlaneConnection(arg1:string,arg2:string,arg3:string):Promise<plane.ConnectionStatus>;

export function ToggleMaximiseMainWindow():Promise<void>;

export function ToolResultForTab(arg1:string,arg2:string):Promise<Record<string, any>>;

export function TrashTopic(arg1:string):Promise<void>;

export function TrustProjectHooks():Promise<Record<string, any>>;

export function TrustProjectHooksForRoot(arg1:any):Promise<Record<string, any>>;

export function TrySubagentProfile(arg1:any,arg2:any):Promise<Record<string, any>>;

export function UpdateMCPServer(arg1:any,arg2:any):Promise<Record<string, any>>;

export function UpdatePlugin(arg1:any):Promise<Record<string, any>>;

export function UpdateRemoteHost(arg1:any,arg2:any):Promise<Record<string, any>>;

export function UpdateSubagentProfile(arg1:any,arg2:any,arg3:any):Promise<Record<string, any>>;

export function ValidateTransition(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<string>;

export function Version():Promise<string>;

export function WorkbenchActiveTarget():Promise<Record<string, any>>;

export function WorkbenchConnectRemote(arg1:any,arg2:any):Promise<Record<string, any>>;

export function WorkbenchDisconnectRemote():Promise<Record<string, any>>;

export function WorkbenchLastRemoteHint():Promise<Record<string, any>>;

export function WorkbenchPendingProviderTrust():Promise<any>;

export function WorkbenchRemoteRequest(arg1:any,arg2:any):Promise<Record<string, any>>;

export function WorkbenchResolveProviderTrust(arg1:any):Promise<Record<string, any>>;

export function WorkbenchSwitchLocal():Promise<Record<string, any>>;

export function WorkspaceChangeDetail(arg1:any,arg2:any):Promise<void>;

export function WorkspaceChanges(arg1:string):Promise<Record<string, any>>;

export function WorkspaceGitCommitDetail(arg1:any,arg2:any,arg3:any):Promise<void>;

export function WorkspaceGitHistory(arg1:any,arg2:any):Promise<void>;

export function WriteRemoteFile(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function WriteTerminalForTab(arg1:string,arg2:string,arg3:string):Promise<void>;
