// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {engine} from '../models';
import {gitrepo} from '../models';
import {storage} from '../models';
import {plane} from '../models';
import {bridge} from '../models';
import {taskspace} from '../models';
import {execution} from '../models';
import {report} from '../models';

export function AbortAgentRun(arg1:agent.AbortRequest):Promise<void>;

export function AgentSessionCommand(arg1:agent.CommandRequest):Promise<Record<string, any>>;

export function AnalyzePlaneCandidate(arg1:string,arg2:engine.PISettings):Promise<engine.CandidateAnalysis>;

export function AnalyzeRequirements(arg1:engine.RequirementAnalysisInput,arg2:engine.PISettings):Promise<engine.RequirementAnalysisResult>;

export function AnswerQuestionForTab(arg1:string,arg2:string,arg3:Array<any>):Promise<void>;

export function ApproveTab(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function BalanceForTab(arg1:string):Promise<Record<string, any>>;

export function BindGitRepository(arg1:gitrepo.BindRequest):Promise<storage.GitBindingRecord>;

export function CancelTab(arg1:string):Promise<void>;

export function Capabilities():Promise<Record<string, any>>;

export function CheckUpdate(arg1:any):Promise<Record<string, any>>;

export function CheckpointsForTab(arg1:string):Promise<Array<any>>;

export function CleanupTaskGitWorktree(arg1:gitrepo.CleanupRequest):Promise<storage.GitBindingRecord>;

export function ClearGoalForTab(arg1:string):Promise<void>;

export function ClearSession():Promise<void>;

export function ClearSessionForTab(arg1:string):Promise<void>;

export function ClearState():Promise<void>;

export function CloseMainWindow():Promise<void>;

export function CollectPlaneWorkItems(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<plane.Candidate>>;

export function Commands():Promise<Array<Record<string, any>>>;

export function CommitTaskGitChanges(arg1:gitrepo.CommitRequest):Promise<gitrepo.CommitResult>;

export function CompactForTab(arg1:string):Promise<void>;

export function ContextPanel(arg1:string):Promise<Record<string, any>>;

export function ContextUsageForTab(arg1:string):Promise<Record<string, any>>;

export function CreateAgentSession(arg1:agent.CreateSessionRequest):Promise<storage.AgentSessionRecord>;

export function CreateTopic(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function DeleteDailyReportToken(arg1:string,arg2:string):Promise<void>;

export function DeletePlaneToken(arg1:string,arg2:string):Promise<void>;

export function DeleteRecoveryCopy(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DesktopStartupSettings():Promise<Record<string, any>>;

export function Effort():Promise<Record<string, any>>;

export function EffortForTab(arg1:string):Promise<Record<string, any>>;

export function EngineStatuses():Promise<Array<engine.Status>>;

export function EnsureBlankSurface(arg1:string):Promise<bridge.TabView>;

export function EnsureBlankTab(arg1:string,arg2:string):Promise<bridge.TabView>;

export function EnsureTaskWorkspace(arg1:string):Promise<storage.TaskWorkspaceRecord>;

export function ExternalOpeners():Promise<Record<string, any>>;

export function FollowUpAgent(arg1:agent.PromptRequest):Promise<storage.AgentMessageRecord>;

export function Forget(arg1:string):Promise<void>;

export function ForgetForTab(arg1:string,arg2:string):Promise<void>;

export function ForkForTab(arg1:string,arg2:number):Promise<bridge.TabView>;

export function GenerateDailyReport(arg1:engine.DailyReportGenerationInput,arg2:engine.PISettings):Promise<engine.DailyReportGenerationResult>;

export function GetActiveThemePack():Promise<any>;

export function GetAgentHistoryPage(arg1:agent.HistoryPageRequest):Promise<agent.HistoryPage>;

export function GetDesktopZoomFactor():Promise<number>;

export function GetTaskContextRoot():Promise<storage.TaskContextRootInfo>;

export function GetTaskFileDiff(arg1:string,arg2:string):Promise<gitrepo.FileDiffView>;

export function GetTaskGitStatus(arg1:string):Promise<gitrepo.StatusView>;

export function GetThemeExperience():Promise<Record<string, any>>;

export function HasDailyReportToken(arg1:string,arg2:string):Promise<boolean>;

export function HasPlaneToken(arg1:string,arg2:string):Promise<boolean>;

export function HeartbeatGenerateID():Promise<string>;

export function HeartbeatListTasks():Promise<Array<any>>;

export function HeartbeatReloadTasks():Promise<Array<any>>;

export function HeartbeatSaveTasks(arg1:any):Promise<void>;

export function HeartbeatTriggerNow(arg1:string):Promise<void>;

export function HistoryCheckpointTurnsForTab(arg1:string):Promise<Array<number>>;

export function HistoryForTab(arg1:string):Promise<Array<bridge.HistoryMessageView>>;

export function HistoryPageForTab(arg1:string,arg2:number,arg3:number):Promise<bridge.HistoryPageView>;

export function ImportAgentAttachments(arg1:agent.ImportAttachmentsRequest):Promise<Array<agent.ResourceDescriptor>>;

export function IsMainWindowMaximised():Promise<boolean>;

export function JobsForTab(arg1:string):Promise<Array<any>>;

export function LaunchReasonix():Promise<void>;

export function ListAgentArtifacts(arg1:string):Promise<Array<agent.ResourceDescriptor>>;

export function ListAgentMessages(arg1:string,arg2:string):Promise<Array<storage.AgentMessageRecord>>;

export function ListAgentPermissionGrants(arg1:string,arg2:string):Promise<Array<storage.PermissionGrantRecord>>;

export function ListAgentPermissionRequests(arg1:string,arg2:string):Promise<Array<agent.PermissionRequest>>;

export function ListAgentResources(arg1:agent.ResourceSearchRequest):Promise<Array<agent.ResourceDescriptor>>;

export function ListAgentSessions(arg1:string):Promise<Array<storage.AgentSessionRecord>>;

export function ListAgentToolCalls(arg1:string,arg2:string):Promise<Array<storage.ToolCallRecord>>;

export function ListDirForTab(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function ListExecutionRuns(arg1:string,arg2:string):Promise<Array<storage.ExecutionRunRecord>>;

export function ListPlaneProjects(arg1:string,arg2:string):Promise<Array<plane.Project>>;

export function ListProjectTree():Promise<Array<any>>;

export function ListSessions():Promise<Array<bridge.SessionMetaView>>;

export function ListTabs():Promise<Array<bridge.TabView>>;

export function ListTaskWorkspaceFiles(arg1:string,arg2:string):Promise<Array<taskspace.WorkspaceEntry>>;

export function ListTrashedSessions():Promise<Array<bridge.SessionMetaView>>;

export function ListWorkspaces():Promise<Array<any>>;

export function LoadPlaneWorkItemDetails(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<plane.Candidate>;

export function LoadState():Promise<string>;

export function MemoryForTab(arg1:string):Promise<Record<string, any>>;

export function Meta():Promise<bridge.MetaView>;

export function MetaForTab(arg1:string):Promise<bridge.MetaView>;

export function MinimiseMainWindow():Promise<void>;

export function Models():Promise<Array<bridge.ModelInfoView>>;

export function ModelsForTab(arg1:string):Promise<Array<bridge.ModelInfoView>>;

export function NeedsOnboarding():Promise<boolean>;

export function NewSession():Promise<void>;

export function NewSessionForTab(arg1:string):Promise<void>;

export function OpenAgentArtifact(arg1:string,arg2:string):Promise<void>;

export function OpenGlobalTab(arg1:string):Promise<bridge.TabView>;

export function OpenTaskContextRoot():Promise<void>;

export function OpenWorkspacePathForTab(arg1:string,arg2:string):Promise<void>;

export function Platform():Promise<string>;

export function PreviewAgentResource(arg1:agent.ResourcePreviewRequest):Promise<taskspace.FilePreview>;

export function PreviewSession(arg1:string):Promise<Array<bridge.HistoryMessageView>>;

export function ReadAgentToolOutput(arg1:agent.ToolOutputRequest):Promise<agent.ToolOutput>;

export function ReadFileForTab(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ReadTaskWorkspaceFile(arg1:string,arg2:string):Promise<taskspace.FilePreview>;

export function ReasonixCloseTab(arg1:string):Promise<void>;

export function ReasonixEnsureTab(arg1:string,arg2:string,arg3:string):Promise<bridge.TabView>;

export function RecoverTaskGitWorktree(arg1:gitrepo.RecoverRequest):Promise<storage.GitBindingRecord>;

export function Remember(arg1:string,arg2:string):Promise<string>;

export function RememberForTab(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RemoteConnectionStatuses():Promise<Array<any>>;

export function RemoteHosts():Promise<Array<any>>;

export function RemoveAgentMessageReference(arg1:agent.RemoveReferenceRequest):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ReplayPendingPrompts():Promise<void>;

export function ResolveAgentPermission(arg1:agent.ResolvePermissionRequest):Promise<agent.PermissionRequest>;

export function ResolveRecoveryTab(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ResumeAgentSession(arg1:agent.SessionRequest):Promise<storage.AgentSessionRecord>;

export function ResumeGoalForTab(arg1:string):Promise<boolean>;

export function ResumeSession(arg1:string):Promise<Array<bridge.HistoryMessageView>>;

export function ResumeSessionForTab(arg1:string,arg2:string):Promise<Array<bridge.HistoryMessageView>>;

export function ResumeSessionPage(arg1:string,arg2:number):Promise<bridge.HistoryPageView>;

export function ResumeSessionPageForTab(arg1:string,arg2:string,arg3:number):Promise<bridge.HistoryPageView>;

export function RevokeAgentPermissionGrant(arg1:agent.RevokePermissionGrantRequest):Promise<storage.PermissionGrantRecord>;

export function RewindForTab(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SaveDailyReportToken(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SavePlaneToken(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveState(arg1:string):Promise<void>;

export function ScanPromptHistory(arg1:string):Promise<Record<string, any>>;

export function SearchFileRefsForTab(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function SelectDailyReportProjectDirectory():Promise<string>;

export function SelectGitRepository():Promise<string>;

export function SelectTaskContextRoot():Promise<string>;

export function SendAgentPrompt(arg1:agent.PromptRequest):Promise<storage.ExecutionRunRecord>;

export function SetActiveTab(arg1:string):Promise<void>;

export function SetCollaborationModeForTab(arg1:string,arg2:string):Promise<void>;

export function SetComposerProfileForTab(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function SetEffortForTab(arg1:string,arg2:string):Promise<void>;

export function SetGoalForTab(arg1:string,arg2:string):Promise<void>;

export function SetModeForTab(arg1:string,arg2:string):Promise<Array<string>>;

export function SetModelForTab(arg1:string,arg2:string):Promise<void>;

export function SetTaskContextRoot(arg1:string):Promise<storage.TaskContextRootInfo>;

export function SetTokenModeForTab(arg1:string,arg2:string):Promise<void>;

export function SetToolApprovalModeForTab(arg1:string,arg2:string):Promise<Array<string>>;

export function SetTrayLocale(arg1:string):Promise<void>;

export function Settings():Promise<Record<string, any>>;

export function SetupPlaneConnection(arg1:string,arg2:string):Promise<plane.ConnectionSetup>;

export function SlashArgs(arg1:string):Promise<Record<string, any>>;

export function SteerAgent(arg1:agent.PromptRequest):Promise<storage.AgentMessageRecord>;

export function SteerForTab(arg1:string,arg2:string):Promise<void>;

export function StopAgentToolExecution(arg1:execution.StopRequest):Promise<void>;

export function SubmitDailyReport(arg1:string,arg2:string,arg3:string,arg4:string):Promise<report.SubmitResult>;

export function SubmitInitialGoalToTab(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<any>,arg6:string,arg7:string,arg8:string,arg9:number,arg10:number):Promise<Array<string>>;

export function SubmitToTab(arg1:string,arg2:string):Promise<void>;

export function SummarizeFromForTab(arg1:string,arg2:number):Promise<void>;

export function SummarizeUpToForTab(arg1:string,arg2:number):Promise<void>;

export function TestPlaneConnection(arg1:string,arg2:string,arg3:string):Promise<plane.ConnectionStatus>;

export function ToggleMaximiseMainWindow():Promise<void>;

export function ToolResultForTab(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ValidateTransition(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<string>;

export function WorkbenchActiveTarget():Promise<Record<string, any>>;

export function WorkbenchPendingProviderTrust():Promise<any>;

export function WorkspaceChanges(arg1:string):Promise<Record<string, any>>;
