// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortAgentRun(arg1) {
  return window['go']['main']['App']['AbortAgentRun'](arg1);
}

export function AgentSessionCommand(arg1) {
  return window['go']['main']['App']['AgentSessionCommand'](arg1);
}

export function AnalyzePlaneCandidate(arg1, arg2) {
  return window['go']['main']['App']['AnalyzePlaneCandidate'](arg1, arg2);
}

export function AnalyzeRequirements(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeRequirements'](arg1, arg2);
}

export function AnswerQuestionForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnswerQuestionForTab'](arg1, arg2, arg3);
}

export function ApproveTab(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ApproveTab'](arg1, arg2, arg3, arg4, arg5);
}

export function BalanceForTab(arg1) {
  return window['go']['main']['App']['BalanceForTab'](arg1);
}

export function BindGitRepository(arg1) {
  return window['go']['main']['App']['BindGitRepository'](arg1);
}

export function CancelTab(arg1) {
  return window['go']['main']['App']['CancelTab'](arg1);
}

export function Capabilities() {
  return window['go']['main']['App']['Capabilities']();
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function CheckpointsForTab(arg1) {
  return window['go']['main']['App']['CheckpointsForTab'](arg1);
}

export function CleanupTaskGitWorktree(arg1) {
  return window['go']['main']['App']['CleanupTaskGitWorktree'](arg1);
}

export function ClearGoalForTab(arg1) {
  return window['go']['main']['App']['ClearGoalForTab'](arg1);
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function ClearSessionForTab(arg1) {
  return window['go']['main']['App']['ClearSessionForTab'](arg1);
}

export function ClearState() {
  return window['go']['main']['App']['ClearState']();
}

export function CloseMainWindow() {
  return window['go']['main']['App']['CloseMainWindow']();
}

export function CollectPlaneWorkItems(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CollectPlaneWorkItems'](arg1, arg2, arg3, arg4);
}

export function Commands() {
  return window['go']['main']['App']['Commands']();
}

export function CommitTaskGitChanges(arg1) {
  return window['go']['main']['App']['CommitTaskGitChanges'](arg1);
}

export function CompactForTab(arg1) {
  return window['go']['main']['App']['CompactForTab'](arg1);
}

export function ContextPanel(arg1) {
  return window['go']['main']['App']['ContextPanel'](arg1);
}

export function ContextUsageForTab(arg1) {
  return window['go']['main']['App']['ContextUsageForTab'](arg1);
}

export function CreateAgentSession(arg1) {
  return window['go']['main']['App']['CreateAgentSession'](arg1);
}

export function CreateTopic(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTopic'](arg1, arg2, arg3);
}

export function DeleteDailyReportToken(arg1, arg2) {
  return window['go']['main']['App']['DeleteDailyReportToken'](arg1, arg2);
}

export function DeletePlaneToken(arg1, arg2) {
  return window['go']['main']['App']['DeletePlaneToken'](arg1, arg2);
}

export function DeleteRecoveryCopy(arg1) {
  return window['go']['main']['App']['DeleteRecoveryCopy'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DesktopStartupSettings() {
  return window['go']['main']['App']['DesktopStartupSettings']();
}

export function Effort() {
  return window['go']['main']['App']['Effort']();
}

export function EffortForTab(arg1) {
  return window['go']['main']['App']['EffortForTab'](arg1);
}

export function EngineStatuses() {
  return window['go']['main']['App']['EngineStatuses']();
}

export function EnsureBlankSurface(arg1) {
  return window['go']['main']['App']['EnsureBlankSurface'](arg1);
}

export function EnsureBlankTab(arg1, arg2) {
  return window['go']['main']['App']['EnsureBlankTab'](arg1, arg2);
}

export function EnsureTaskWorkspace(arg1) {
  return window['go']['main']['App']['EnsureTaskWorkspace'](arg1);
}

export function ExternalOpeners() {
  return window['go']['main']['App']['ExternalOpeners']();
}

export function FollowUpAgent(arg1) {
  return window['go']['main']['App']['FollowUpAgent'](arg1);
}

export function Forget(arg1) {
  return window['go']['main']['App']['Forget'](arg1);
}

export function ForgetForTab(arg1, arg2) {
  return window['go']['main']['App']['ForgetForTab'](arg1, arg2);
}

export function ForkForTab(arg1, arg2) {
  return window['go']['main']['App']['ForkForTab'](arg1, arg2);
}

export function GenerateDailyReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateDailyReport'](arg1, arg2);
}

export function GetActiveThemePack() {
  return window['go']['main']['App']['GetActiveThemePack']();
}

export function GetAgentHistoryPage(arg1) {
  return window['go']['main']['App']['GetAgentHistoryPage'](arg1);
}

export function GetDesktopZoomFactor() {
  return window['go']['main']['App']['GetDesktopZoomFactor']();
}

export function GetTaskContextRoot() {
  return window['go']['main']['App']['GetTaskContextRoot']();
}

export function GetTaskFileDiff(arg1, arg2) {
  return window['go']['main']['App']['GetTaskFileDiff'](arg1, arg2);
}

export function GetTaskGitStatus(arg1) {
  return window['go']['main']['App']['GetTaskGitStatus'](arg1);
}

export function GetThemeExperience() {
  return window['go']['main']['App']['GetThemeExperience']();
}

export function HasDailyReportToken(arg1, arg2) {
  return window['go']['main']['App']['HasDailyReportToken'](arg1, arg2);
}

export function HasPlaneToken(arg1, arg2) {
  return window['go']['main']['App']['HasPlaneToken'](arg1, arg2);
}

export function HeartbeatGenerateID() {
  return window['go']['main']['App']['HeartbeatGenerateID']();
}

export function HeartbeatListTasks() {
  return window['go']['main']['App']['HeartbeatListTasks']();
}

export function HeartbeatReloadTasks() {
  return window['go']['main']['App']['HeartbeatReloadTasks']();
}

export function HeartbeatSaveTasks(arg1) {
  return window['go']['main']['App']['HeartbeatSaveTasks'](arg1);
}

export function HeartbeatTriggerNow(arg1) {
  return window['go']['main']['App']['HeartbeatTriggerNow'](arg1);
}

export function HistoryCheckpointTurnsForTab(arg1) {
  return window['go']['main']['App']['HistoryCheckpointTurnsForTab'](arg1);
}

export function HistoryForTab(arg1) {
  return window['go']['main']['App']['HistoryForTab'](arg1);
}

export function HistoryPageForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['HistoryPageForTab'](arg1, arg2, arg3);
}

export function ImportAgentAttachments(arg1) {
  return window['go']['main']['App']['ImportAgentAttachments'](arg1);
}

export function IsMainWindowMaximised() {
  return window['go']['main']['App']['IsMainWindowMaximised']();
}

export function JobsForTab(arg1) {
  return window['go']['main']['App']['JobsForTab'](arg1);
}

export function LaunchReasonix() {
  return window['go']['main']['App']['LaunchReasonix']();
}

export function ListAgentArtifacts(arg1) {
  return window['go']['main']['App']['ListAgentArtifacts'](arg1);
}

export function ListAgentMessages(arg1, arg2) {
  return window['go']['main']['App']['ListAgentMessages'](arg1, arg2);
}

export function ListAgentPermissionGrants(arg1, arg2) {
  return window['go']['main']['App']['ListAgentPermissionGrants'](arg1, arg2);
}

export function ListAgentPermissionRequests(arg1, arg2) {
  return window['go']['main']['App']['ListAgentPermissionRequests'](arg1, arg2);
}

export function ListAgentResources(arg1) {
  return window['go']['main']['App']['ListAgentResources'](arg1);
}

export function ListAgentSessions(arg1) {
  return window['go']['main']['App']['ListAgentSessions'](arg1);
}

export function ListAgentToolCalls(arg1, arg2) {
  return window['go']['main']['App']['ListAgentToolCalls'](arg1, arg2);
}

export function ListDirForTab(arg1, arg2) {
  return window['go']['main']['App']['ListDirForTab'](arg1, arg2);
}

export function ListExecutionRuns(arg1, arg2) {
  return window['go']['main']['App']['ListExecutionRuns'](arg1, arg2);
}

export function ListPlaneProjects(arg1, arg2) {
  return window['go']['main']['App']['ListPlaneProjects'](arg1, arg2);
}

export function ListProjectTree() {
  return window['go']['main']['App']['ListProjectTree']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListTabs() {
  return window['go']['main']['App']['ListTabs']();
}

export function ListTaskWorkspaceFiles(arg1, arg2) {
  return window['go']['main']['App']['ListTaskWorkspaceFiles'](arg1, arg2);
}

export function ListTrashedSessions() {
  return window['go']['main']['App']['ListTrashedSessions']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function LoadPlaneWorkItemDetails(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LoadPlaneWorkItemDetails'](arg1, arg2, arg3, arg4, arg5);
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function MemoryForTab(arg1) {
  return window['go']['main']['App']['MemoryForTab'](arg1);
}

export function Meta() {
  return window['go']['main']['App']['Meta']();
}

export function MetaForTab(arg1) {
  return window['go']['main']['App']['MetaForTab'](arg1);
}

export function MinimiseMainWindow() {
  return window['go']['main']['App']['MinimiseMainWindow']();
}

export function Models() {
  return window['go']['main']['App']['Models']();
}

export function ModelsForTab(arg1) {
  return window['go']['main']['App']['ModelsForTab'](arg1);
}

export function NeedsOnboarding() {
  return window['go']['main']['App']['NeedsOnboarding']();
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function NewSessionForTab(arg1) {
  return window['go']['main']['App']['NewSessionForTab'](arg1);
}

export function OpenAgentArtifact(arg1, arg2) {
  return window['go']['main']['App']['OpenAgentArtifact'](arg1, arg2);
}

export function OpenGlobalTab(arg1) {
  return window['go']['main']['App']['OpenGlobalTab'](arg1);
}

export function OpenTaskContextRoot() {
  return window['go']['main']['App']['OpenTaskContextRoot']();
}

export function OpenWorkspacePathForTab(arg1, arg2) {
  return window['go']['main']['App']['OpenWorkspacePathForTab'](arg1, arg2);
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function PreviewAgentResource(arg1) {
  return window['go']['main']['App']['PreviewAgentResource'](arg1);
}

export function PreviewSession(arg1) {
  return window['go']['main']['App']['PreviewSession'](arg1);
}

export function ReadAgentToolOutput(arg1) {
  return window['go']['main']['App']['ReadAgentToolOutput'](arg1);
}

export function ReadFileForTab(arg1, arg2) {
  return window['go']['main']['App']['ReadFileForTab'](arg1, arg2);
}

export function ReadTaskWorkspaceFile(arg1, arg2) {
  return window['go']['main']['App']['ReadTaskWorkspaceFile'](arg1, arg2);
}

export function ReasonixCloseTab(arg1) {
  return window['go']['main']['App']['ReasonixCloseTab'](arg1);
}

export function ReasonixEnsureTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReasonixEnsureTab'](arg1, arg2, arg3);
}

export function RecoverTaskGitWorktree(arg1) {
  return window['go']['main']['App']['RecoverTaskGitWorktree'](arg1);
}

export function Remember(arg1, arg2) {
  return window['go']['main']['App']['Remember'](arg1, arg2);
}

export function RememberForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['RememberForTab'](arg1, arg2, arg3);
}

export function RemoteConnectionStatuses() {
  return window['go']['main']['App']['RemoteConnectionStatuses']();
}

export function RemoteHosts() {
  return window['go']['main']['App']['RemoteHosts']();
}

export function RemoveAgentMessageReference(arg1) {
  return window['go']['main']['App']['RemoveAgentMessageReference'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ReplayPendingPrompts() {
  return window['go']['main']['App']['ReplayPendingPrompts']();
}

export function ResolveAgentPermission(arg1) {
  return window['go']['main']['App']['ResolveAgentPermission'](arg1);
}

export function ResolveRecoveryTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResolveRecoveryTab'](arg1, arg2, arg3, arg4);
}

export function ResumeAgentSession(arg1) {
  return window['go']['main']['App']['ResumeAgentSession'](arg1);
}

export function ResumeGoalForTab(arg1) {
  return window['go']['main']['App']['ResumeGoalForTab'](arg1);
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function ResumeSessionForTab(arg1, arg2) {
  return window['go']['main']['App']['ResumeSessionForTab'](arg1, arg2);
}

export function ResumeSessionPage(arg1, arg2) {
  return window['go']['main']['App']['ResumeSessionPage'](arg1, arg2);
}

export function ResumeSessionPageForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResumeSessionPageForTab'](arg1, arg2, arg3);
}

export function RevokeAgentPermissionGrant(arg1) {
  return window['go']['main']['App']['RevokeAgentPermissionGrant'](arg1);
}

export function RewindForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['RewindForTab'](arg1, arg2, arg3);
}

export function SaveDailyReportToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDailyReportToken'](arg1, arg2, arg3);
}

export function SavePlaneToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePlaneToken'](arg1, arg2, arg3);
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}

export function ScanPromptHistory(arg1) {
  return window['go']['main']['App']['ScanPromptHistory'](arg1);
}

export function SearchFileRefsForTab(arg1, arg2) {
  return window['go']['main']['App']['SearchFileRefsForTab'](arg1, arg2);
}

export function SelectDailyReportProjectDirectory() {
  return window['go']['main']['App']['SelectDailyReportProjectDirectory']();
}

export function SelectGitRepository() {
  return window['go']['main']['App']['SelectGitRepository']();
}

export function SelectTaskContextRoot() {
  return window['go']['main']['App']['SelectTaskContextRoot']();
}

export function SendAgentPrompt(arg1) {
  return window['go']['main']['App']['SendAgentPrompt'](arg1);
}

export function SetActiveTab(arg1) {
  return window['go']['main']['App']['SetActiveTab'](arg1);
}

export function SetCollaborationModeForTab(arg1, arg2) {
  return window['go']['main']['App']['SetCollaborationModeForTab'](arg1, arg2);
}

export function SetComposerProfileForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetComposerProfileForTab'](arg1, arg2, arg3, arg4);
}

export function SetEffortForTab(arg1, arg2) {
  return window['go']['main']['App']['SetEffortForTab'](arg1, arg2);
}

export function SetGoalForTab(arg1, arg2) {
  return window['go']['main']['App']['SetGoalForTab'](arg1, arg2);
}

export function SetModeForTab(arg1, arg2) {
  return window['go']['main']['App']['SetModeForTab'](arg1, arg2);
}

export function SetModelForTab(arg1, arg2) {
  return window['go']['main']['App']['SetModelForTab'](arg1, arg2);
}

export function SetTaskContextRoot(arg1) {
  return window['go']['main']['App']['SetTaskContextRoot'](arg1);
}

export function SetTokenModeForTab(arg1, arg2) {
  return window['go']['main']['App']['SetTokenModeForTab'](arg1, arg2);
}

export function SetToolApprovalModeForTab(arg1, arg2) {
  return window['go']['main']['App']['SetToolApprovalModeForTab'](arg1, arg2);
}

export function SetTrayLocale(arg1) {
  return window['go']['main']['App']['SetTrayLocale'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function SetupPlaneConnection(arg1, arg2) {
  return window['go']['main']['App']['SetupPlaneConnection'](arg1, arg2);
}

export function SlashArgs(arg1) {
  return window['go']['main']['App']['SlashArgs'](arg1);
}

export function SteerAgent(arg1) {
  return window['go']['main']['App']['SteerAgent'](arg1);
}

export function SteerForTab(arg1, arg2) {
  return window['go']['main']['App']['SteerForTab'](arg1, arg2);
}

export function StopAgentToolExecution(arg1) {
  return window['go']['main']['App']['StopAgentToolExecution'](arg1);
}

export function SubmitDailyReport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubmitDailyReport'](arg1, arg2, arg3, arg4);
}

export function SubmitInitialGoalToTab(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['SubmitInitialGoalToTab'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SubmitToTab(arg1, arg2) {
  return window['go']['main']['App']['SubmitToTab'](arg1, arg2);
}

export function SummarizeFromForTab(arg1, arg2) {
  return window['go']['main']['App']['SummarizeFromForTab'](arg1, arg2);
}

export function SummarizeUpToForTab(arg1, arg2) {
  return window['go']['main']['App']['SummarizeUpToForTab'](arg1, arg2);
}

export function TestPlaneConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestPlaneConnection'](arg1, arg2, arg3);
}

export function ToggleMaximiseMainWindow() {
  return window['go']['main']['App']['ToggleMaximiseMainWindow']();
}

export function ToolResultForTab(arg1, arg2) {
  return window['go']['main']['App']['ToolResultForTab'](arg1, arg2);
}

export function ValidateTransition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ValidateTransition'](arg1, arg2, arg3, arg4, arg5);
}

export function WorkbenchActiveTarget() {
  return window['go']['main']['App']['WorkbenchActiveTarget']();
}

export function WorkbenchPendingProviderTrust() {
  return window['go']['main']['App']['WorkbenchPendingProviderTrust']();
}

export function WorkspaceChanges(arg1) {
  return window['go']['main']['App']['WorkspaceChanges'](arg1);
}
