// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortAgentRun(arg1) {
  return window['go']['main']['App']['AbortAgentRun'](arg1);
}

export function AcceptMemorySuggestion(arg1) {
  return window['go']['main']['App']['AcceptMemorySuggestion'](arg1);
}

export function AcceptMemorySuggestionForTab(arg1, arg2) {
  return window['go']['main']['App']['AcceptMemorySuggestionForTab'](arg1, arg2);
}

export function AcceptSkillSuggestion(arg1) {
  return window['go']['main']['App']['AcceptSkillSuggestion'](arg1);
}

export function AcceptSkillSuggestionForTab(arg1, arg2) {
  return window['go']['main']['App']['AcceptSkillSuggestionForTab'](arg1, arg2);
}

export function ActivateBaseStyle(arg1) {
  return window['go']['main']['App']['ActivateBaseStyle'](arg1);
}

export function ActivateReasonixTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ActivateReasonixTask'](arg1, arg2, arg3, arg4);
}

export function ActivateThemePack(arg1) {
  return window['go']['main']['App']['ActivateThemePack'](arg1);
}

export function ActivateTopic(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ActivateTopic'](arg1, arg2, arg3, arg4);
}

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function AddOfficialProviderAccess(arg1, arg2) {
  return window['go']['main']['App']['AddOfficialProviderAccess'](arg1, arg2);
}

export function AddPermissionRule(arg1, arg2) {
  return window['go']['main']['App']['AddPermissionRule'](arg1, arg2);
}

export function AddProviderPresetAccess(arg1, arg2) {
  return window['go']['main']['App']['AddProviderPresetAccess'](arg1, arg2);
}

export function AddRemoteForward(arg1, arg2) {
  return window['go']['main']['App']['AddRemoteForward'](arg1, arg2);
}

export function AddRemoteHost(arg1) {
  return window['go']['main']['App']['AddRemoteHost'](arg1);
}

export function AddSkillPath(arg1) {
  return window['go']['main']['App']['AddSkillPath'](arg1);
}

export function AgentSessionCommand(arg1) {
  return window['go']['main']['App']['AgentSessionCommand'](arg1);
}

export function AnalyzePlaneCandidate(arg1, arg2) {
  return window['go']['main']['App']['AnalyzePlaneCandidate'](arg1, arg2);
}

export function AnalyzeRequirements(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeRequirements'](arg1, arg2);
}

export function AnswerQuestion(arg1, arg2) {
  return window['go']['main']['App']['AnswerQuestion'](arg1, arg2);
}

export function AnswerQuestionForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnswerQuestionForTab'](arg1, arg2, arg3);
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function Approve(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Approve'](arg1, arg2, arg3, arg4);
}

export function ApproveTab(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ApproveTab'](arg1, arg2, arg3, arg4, arg5);
}

export function AttachDropped(arg1) {
  return window['go']['main']['App']['AttachDropped'](arg1);
}

export function AttachmentDataURL(arg1) {
  return window['go']['main']['App']['AttachmentDataURL'](arg1);
}

export function AuthorizeAndConnectMCPServer(arg1) {
  return window['go']['main']['App']['AuthorizeAndConnectMCPServer'](arg1);
}

export function AutoResearchCurrent() {
  return window['go']['main']['App']['AutoResearchCurrent']();
}

export function AutoResearchFindings(arg1, arg2) {
  return window['go']['main']['App']['AutoResearchFindings'](arg1, arg2);
}

export function AutoResearchList(arg1) {
  return window['go']['main']['App']['AutoResearchList'](arg1);
}

export function AutoResearchOpenTask(arg1) {
  return window['go']['main']['App']['AutoResearchOpenTask'](arg1);
}

export function AutoResearchRecordEvidence(arg1, arg2, arg3) {
  return window['go']['main']['App']['AutoResearchRecordEvidence'](arg1, arg2, arg3);
}

export function AutoResearchStatus(arg1) {
  return window['go']['main']['App']['AutoResearchStatus'](arg1);
}

export function AvailableSubagentTools() {
  return window['go']['main']['App']['AvailableSubagentTools']();
}

export function Balance() {
  return window['go']['main']['App']['Balance']();
}

export function BalanceForTab(arg1) {
  return window['go']['main']['App']['BalanceForTab'](arg1);
}

export function BindGitRepository(arg1) {
  return window['go']['main']['App']['BindGitRepository'](arg1);
}

export function BotRuntimeStatus() {
  return window['go']['main']['App']['BotRuntimeStatus']();
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function CancelForTab(arg1) {
  return window['go']['main']['App']['CancelForTab'](arg1);
}

export function CancelTab(arg1) {
  return window['go']['main']['App']['CancelTab'](arg1);
}

export function CancelTrySubagentProfile() {
  return window['go']['main']['App']['CancelTrySubagentProfile']();
}

export function Capabilities() {
  return window['go']['main']['App']['Capabilities']();
}

export function CapabilityDiagnostics(arg1) {
  return window['go']['main']['App']['CapabilityDiagnostics'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function Checkpoints() {
  return window['go']['main']['App']['Checkpoints']();
}

export function CheckpointsForTab(arg1) {
  return window['go']['main']['App']['CheckpointsForTab'](arg1);
}

export function CleanupTaskGitWorktree(arg1) {
  return window['go']['main']['App']['CleanupTaskGitWorktree'](arg1);
}

export function ClearBotSecret(arg1) {
  return window['go']['main']['App']['ClearBotSecret'](arg1);
}

export function ClearGoal() {
  return window['go']['main']['App']['ClearGoal']();
}

export function ClearGoalForTab(arg1) {
  return window['go']['main']['App']['ClearGoalForTab'](arg1);
}

export function ClearMCPServerAuthentication(arg1) {
  return window['go']['main']['App']['ClearMCPServerAuthentication'](arg1);
}

export function ClearProviderKey(arg1) {
  return window['go']['main']['App']['ClearProviderKey'](arg1);
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function ClearSessionForTab(arg1) {
  return window['go']['main']['App']['ClearSessionForTab'](arg1);
}

export function ClearState() {
  return window['go']['main']['App']['ClearState']();
}

export function CloseMainWindow() {
  return window['go']['main']['App']['CloseMainWindow']();
}

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function CloseTerminalForTab(arg1, arg2) {
  return window['go']['main']['App']['CloseTerminalForTab'](arg1, arg2);
}

export function CollectPlaneWorkItems(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CollectPlaneWorkItems'](arg1, arg2, arg3, arg4, arg5);
}

export function Commands() {
  return window['go']['main']['App']['Commands']();
}

export function CommitTaskGitChanges(arg1) {
  return window['go']['main']['App']['CommitTaskGitChanges'](arg1);
}

export function Compact() {
  return window['go']['main']['App']['Compact']();
}

export function CompactForTab(arg1) {
  return window['go']['main']['App']['CompactForTab'](arg1);
}

export function ConfirmAction(arg1) {
  return window['go']['main']['App']['ConfirmAction'](arg1);
}

export function ConfirmRemoteHostKey(arg1, arg2) {
  return window['go']['main']['App']['ConfirmRemoteHostKey'](arg1, arg2);
}

export function ConfirmRemoteSecret(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConfirmRemoteSecret'](arg1, arg2, arg3, arg4);
}

export function ConnectKey(arg1) {
  return window['go']['main']['App']['ConnectKey'](arg1);
}

export function ConnectRemoteHost(arg1) {
  return window['go']['main']['App']['ConnectRemoteHost'](arg1);
}

export function ContextPanel(arg1) {
  return window['go']['main']['App']['ContextPanel'](arg1);
}

export function ContextUsage() {
  return window['go']['main']['App']['ContextUsage']();
}

export function ContextUsageForTab(arg1) {
  return window['go']['main']['App']['ContextUsageForTab'](arg1);
}

export function CopyThemePack(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyThemePack'](arg1, arg2, arg3);
}

export function CreateAgentSession(arg1) {
  return window['go']['main']['App']['CreateAgentSession'](arg1);
}

export function CreateDeliveryWorktree(arg1) {
  return window['go']['main']['App']['CreateDeliveryWorktree'](arg1);
}

export function CreateSubagentProfile(arg1) {
  return window['go']['main']['App']['CreateSubagentProfile'](arg1);
}

export function CreateTerminalForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTerminalForTab'](arg1, arg2, arg3);
}

export function CreateTopic(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTopic'](arg1, arg2, arg3);
}

export function DeleteDailyReportToken(arg1, arg2) {
  return window['go']['main']['App']['DeleteDailyReportToken'](arg1, arg2);
}

export function DeletePlaneToken(arg1, arg2) {
  return window['go']['main']['App']['DeletePlaneToken'](arg1, arg2);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteRecoveryCopy(arg1) {
  return window['go']['main']['App']['DeleteRecoveryCopy'](arg1);
}

export function DeleteRemotePath(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRemotePath'](arg1, arg2, arg3);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSubagentProfile(arg1, arg2) {
  return window['go']['main']['App']['DeleteSubagentProfile'](arg1, arg2);
}

export function DeleteThemePack(arg1) {
  return window['go']['main']['App']['DeleteThemePack'](arg1);
}

export function DeleteTopic(arg1) {
  return window['go']['main']['App']['DeleteTopic'](arg1);
}

export function DeliveryWorktreeAvailability(arg1) {
  return window['go']['main']['App']['DeliveryWorktreeAvailability'](arg1);
}

export function DesktopStartupSettings() {
  return window['go']['main']['App']['DesktopStartupSettings']();
}

export function DiagnoseBotConnection(arg1) {
  return window['go']['main']['App']['DiagnoseBotConnection'](arg1);
}

export function DisableThemePack() {
  return window['go']['main']['App']['DisableThemePack']();
}

export function DisconnectRemoteHost(arg1) {
  return window['go']['main']['App']['DisconnectRemoteHost'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function DownloadUpdateRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadUpdateRequest'](arg1, arg2, arg3);
}

export function Effort() {
  return window['go']['main']['App']['Effort']();
}

export function EffortForTab(arg1) {
  return window['go']['main']['App']['EffortForTab'](arg1);
}

export function EngineStatuses() {
  return window['go']['main']['App']['EngineStatuses']();
}

export function EnsureBlankSurface(arg1, arg2) {
  return window['go']['main']['App']['EnsureBlankSurface'](arg1, arg2);
}

export function EnsureBlankTab(arg1, arg2) {
  return window['go']['main']['App']['EnsureBlankTab'](arg1, arg2);
}

export function EnsureRemoteServer(arg1, arg2) {
  return window['go']['main']['App']['EnsureRemoteServer'](arg1, arg2);
}

export function EnsureTaskWorkspace(arg1) {
  return window['go']['main']['App']['EnsureTaskWorkspace'](arg1);
}

export function ExportThemePack(arg1, arg2) {
  return window['go']['main']['App']['ExportThemePack'](arg1, arg2);
}

export function ExternalOpeners() {
  return window['go']['main']['App']['ExternalOpeners']();
}

export function FetchProviderModels(arg1) {
  return window['go']['main']['App']['FetchProviderModels'](arg1);
}

export function FollowUpAgent(arg1) {
  return window['go']['main']['App']['FollowUpAgent'](arg1);
}

export function Forget(arg1) {
  return window['go']['main']['App']['Forget'](arg1);
}

export function ForgetForTab(arg1, arg2) {
  return window['go']['main']['App']['ForgetForTab'](arg1, arg2);
}

export function Fork(arg1) {
  return window['go']['main']['App']['Fork'](arg1);
}

export function ForkForTab(arg1, arg2) {
  return window['go']['main']['App']['ForkForTab'](arg1, arg2);
}

export function GenerateDailyReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateDailyReport'](arg1, arg2);
}

export function GetActiveThemePack() {
  return window['go']['main']['App']['GetActiveThemePack']();
}

export function GetAgentHistoryPage(arg1) {
  return window['go']['main']['App']['GetAgentHistoryPage'](arg1);
}

export function GetDesktopZoomFactor() {
  return window['go']['main']['App']['GetDesktopZoomFactor']();
}

export function GetTaskContextRoot() {
  return window['go']['main']['App']['GetTaskContextRoot']();
}

export function GetTaskFileDiff(arg1, arg2) {
  return window['go']['main']['App']['GetTaskFileDiff'](arg1, arg2);
}

export function GetTaskGitStatus(arg1) {
  return window['go']['main']['App']['GetTaskGitStatus'](arg1);
}

export function GetThemeExperience() {
  return window['go']['main']['App']['GetThemeExperience']();
}

export function GitBranches() {
  return window['go']['main']['App']['GitBranches']();
}

export function GitCheckout(arg1) {
  return window['go']['main']['App']['GitCheckout'](arg1);
}

export function HasDailyReportToken(arg1, arg2) {
  return window['go']['main']['App']['HasDailyReportToken'](arg1, arg2);
}

export function HasPlaneToken(arg1, arg2) {
  return window['go']['main']['App']['HasPlaneToken'](arg1, arg2);
}

export function HeartbeatGenerateID() {
  return window['go']['main']['App']['HeartbeatGenerateID']();
}

export function HeartbeatListTasks() {
  return window['go']['main']['App']['HeartbeatListTasks']();
}

export function HeartbeatReloadTasks() {
  return window['go']['main']['App']['HeartbeatReloadTasks']();
}

export function HeartbeatSaveTasks(arg1) {
  return window['go']['main']['App']['HeartbeatSaveTasks'](arg1);
}

export function HeartbeatTriggerNow(arg1) {
  return window['go']['main']['App']['HeartbeatTriggerNow'](arg1);
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function HistoryCheckpointTurnsForTab(arg1) {
  return window['go']['main']['App']['HistoryCheckpointTurnsForTab'](arg1);
}

export function HistoryForTab(arg1) {
  return window['go']['main']['App']['HistoryForTab'](arg1);
}

export function HistoryPage(arg1, arg2) {
  return window['go']['main']['App']['HistoryPage'](arg1, arg2);
}

export function HistoryPageForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['HistoryPageForTab'](arg1, arg2, arg3);
}

export function HooksSettings(arg1) {
  return window['go']['main']['App']['HooksSettings'](arg1);
}

export function ImportAgentAttachments(arg1) {
  return window['go']['main']['App']['ImportAgentAttachments'](arg1);
}

export function ImportThemePack(arg1, arg2) {
  return window['go']['main']['App']['ImportThemePack'](arg1, arg2);
}

export function InstallMCPServer(arg1) {
  return window['go']['main']['App']['InstallMCPServer'](arg1);
}

export function InstallPlugin(arg1, arg2) {
  return window['go']['main']['App']['InstallPlugin'](arg1, arg2);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function InstallUpdateRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallUpdateRequest'](arg1, arg2, arg3);
}

export function IsMainWindowMaximised() {
  return window['go']['main']['App']['IsMainWindowMaximised']();
}

export function Jobs() {
  return window['go']['main']['App']['Jobs']();
}

export function JobsForTab(arg1) {
  return window['go']['main']['App']['JobsForTab'](arg1);
}

export function LaunchReasonix() {
  return window['go']['main']['App']['LaunchReasonix']();
}

export function ListAgentArtifacts(arg1) {
  return window['go']['main']['App']['ListAgentArtifacts'](arg1);
}

export function ListAgentMessages(arg1, arg2) {
  return window['go']['main']['App']['ListAgentMessages'](arg1, arg2);
}

export function ListAgentPermissionGrants(arg1, arg2) {
  return window['go']['main']['App']['ListAgentPermissionGrants'](arg1, arg2);
}

export function ListAgentPermissionRequests(arg1, arg2) {
  return window['go']['main']['App']['ListAgentPermissionRequests'](arg1, arg2);
}

export function ListAgentResources(arg1) {
  return window['go']['main']['App']['ListAgentResources'](arg1);
}

export function ListAgentSessions(arg1) {
  return window['go']['main']['App']['ListAgentSessions'](arg1);
}

export function ListAgentToolCalls(arg1, arg2) {
  return window['go']['main']['App']['ListAgentToolCalls'](arg1, arg2);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function ListDirForTab(arg1, arg2) {
  return window['go']['main']['App']['ListDirForTab'](arg1, arg2);
}

export function ListExecutionRuns(arg1, arg2) {
  return window['go']['main']['App']['ListExecutionRuns'](arg1, arg2);
}

export function ListPlaneProjects(arg1, arg2) {
  return window['go']['main']['App']['ListPlaneProjects'](arg1, arg2);
}

export function ListProjectTree() {
  return window['go']['main']['App']['ListProjectTree']();
}

export function ListRemoteDir(arg1, arg2) {
  return window['go']['main']['App']['ListRemoteDir'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListTabs() {
  return window['go']['main']['App']['ListTabs']();
}

export function ListTaskWorkspaceFiles(arg1, arg2) {
  return window['go']['main']['App']['ListTaskWorkspaceFiles'](arg1, arg2);
}

export function ListThemePacks() {
  return window['go']['main']['App']['ListThemePacks']();
}

export function ListTrashedSessions() {
  return window['go']['main']['App']['ListTrashedSessions']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function LoadPlaneWorkItemDetails(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LoadPlaneWorkItemDetails'](arg1, arg2, arg3, arg4, arg5);
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function MCPMarketplace(arg1) {
  return window['go']['main']['App']['MCPMarketplace'](arg1);
}

export function MCPMarketplaceResolve(arg1) {
  return window['go']['main']['App']['MCPMarketplaceResolve'](arg1);
}

export function MCPServers() {
  return window['go']['main']['App']['MCPServers']();
}

export function Memory() {
  return window['go']['main']['App']['Memory']();
}

export function MemoryForTab(arg1) {
  return window['go']['main']['App']['MemoryForTab'](arg1);
}

export function MemoryRevisions(arg1) {
  return window['go']['main']['App']['MemoryRevisions'](arg1);
}

export function MemoryRevisionsForTab(arg1, arg2) {
  return window['go']['main']['App']['MemoryRevisionsForTab'](arg1, arg2);
}

export function MemorySuggestions() {
  return window['go']['main']['App']['MemorySuggestions']();
}

export function MemorySuggestionsForTab(arg1) {
  return window['go']['main']['App']['MemorySuggestionsForTab'](arg1);
}

export function Meta() {
  return window['go']['main']['App']['Meta']();
}

export function MetaForTab(arg1) {
  return window['go']['main']['App']['MetaForTab'](arg1);
}

export function MigrateDesktopPreferences(arg1, arg2, arg3) {
  return window['go']['main']['App']['MigrateDesktopPreferences'](arg1, arg2, arg3);
}

export function MinimiseMainWindow() {
  return window['go']['main']['App']['MinimiseMainWindow']();
}

export function MkdirRemote(arg1, arg2) {
  return window['go']['main']['App']['MkdirRemote'](arg1, arg2);
}

export function Models() {
  return window['go']['main']['App']['Models']();
}

export function ModelsForTab(arg1) {
  return window['go']['main']['App']['ModelsForTab'](arg1);
}

export function NeedsOnboarding() {
  return window['go']['main']['App']['NeedsOnboarding']();
}

export function NewSession() {
  return window['go']['main']['App']['NewSession']();
}

export function NewSessionForTab(arg1) {
  return window['go']['main']['App']['NewSessionForTab'](arg1);
}

export function OpenAgentArtifact(arg1, arg2) {
  return window['go']['main']['App']['OpenAgentArtifact'](arg1, arg2);
}

export function OpenChannelSessionForTab(arg1, arg2) {
  return window['go']['main']['App']['OpenChannelSessionForTab'](arg1, arg2);
}

export function OpenChannelSessionPageForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenChannelSessionPageForTab'](arg1, arg2, arg3);
}

export function OpenDownloadPage() {
  return window['go']['main']['App']['OpenDownloadPage']();
}

export function OpenGlobalTab(arg1) {
  return window['go']['main']['App']['OpenGlobalTab'](arg1);
}

export function OpenProjectTab(arg1, arg2) {
  return window['go']['main']['App']['OpenProjectTab'](arg1, arg2);
}

export function OpenRemoteWorkspace(arg1, arg2) {
  return window['go']['main']['App']['OpenRemoteWorkspace'](arg1, arg2);
}

export function OpenTaskContextRoot() {
  return window['go']['main']['App']['OpenTaskContextRoot']();
}

export function OpenTopicSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenTopicSession'](arg1, arg2, arg3, arg4);
}

export function OpenWorkspaceInExternalOpener(arg1) {
  return window['go']['main']['App']['OpenWorkspaceInExternalOpener'](arg1);
}

export function OpenWorkspaceInExternalOpenerForTab(arg1, arg2) {
  return window['go']['main']['App']['OpenWorkspaceInExternalOpenerForTab'](arg1, arg2);
}

export function OpenWorkspacePath(arg1) {
  return window['go']['main']['App']['OpenWorkspacePath'](arg1);
}

export function OpenWorkspacePathForTab(arg1, arg2) {
  return window['go']['main']['App']['OpenWorkspacePathForTab'](arg1, arg2);
}

export function PickExportFile(arg1, arg2) {
  return window['go']['main']['App']['PickExportFile'](arg1, arg2);
}

export function PickPluginFolder() {
  return window['go']['main']['App']['PickPluginFolder']();
}

export function PickSkillFolder() {
  return window['go']['main']['App']['PickSkillFolder']();
}

export function PickThemeBackground() {
  return window['go']['main']['App']['PickThemeBackground']();
}

export function PickWorkspace() {
  return window['go']['main']['App']['PickWorkspace']();
}

export function PlanPluginInstall(arg1, arg2) {
  return window['go']['main']['App']['PlanPluginInstall'](arg1, arg2);
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function PluginDoctor(arg1) {
  return window['go']['main']['App']['PluginDoctor'](arg1);
}

export function Plugins() {
  return window['go']['main']['App']['Plugins']();
}

export function PollBotConnectionInstall(arg1) {
  return window['go']['main']['App']['PollBotConnectionInstall'](arg1);
}

export function PreviewAgentResource(arg1) {
  return window['go']['main']['App']['PreviewAgentResource'](arg1);
}

export function PreviewSession(arg1) {
  return window['go']['main']['App']['PreviewSession'](arg1);
}

export function PurgeRecoveryCopy(arg1) {
  return window['go']['main']['App']['PurgeRecoveryCopy'](arg1);
}

export function PurgeTrashedSession(arg1) {
  return window['go']['main']['App']['PurgeTrashedSession'](arg1);
}

export function ReadAgentToolOutput(arg1) {
  return window['go']['main']['App']['ReadAgentToolOutput'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileForTab(arg1, arg2) {
  return window['go']['main']['App']['ReadFileForTab'](arg1, arg2);
}

export function ReadRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['ReadRemoteFile'](arg1, arg2);
}

export function ReadTaskWorkspaceFile(arg1, arg2) {
  return window['go']['main']['App']['ReadTaskWorkspaceFile'](arg1, arg2);
}

export function ReasonixCloseTab(arg1) {
  return window['go']['main']['App']['ReasonixCloseTab'](arg1);
}

export function ReasonixEnsureTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReasonixEnsureTab'](arg1, arg2, arg3);
}

export function ReasonixHomeInfo() {
  return window['go']['main']['App']['ReasonixHomeInfo']();
}

export function ReasonixProviders() {
  return window['go']['main']['App']['ReasonixProviders']();
}

export function ReasonixRemoveProvider(arg1) {
  return window['go']['main']['App']['ReasonixRemoveProvider'](arg1);
}

export function ReasonixSaveProvider(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ReasonixSaveProvider'](arg1, arg2, arg3, arg4, arg5);
}

export function ReasonixSetApprovalMode(arg1) {
  return window['go']['main']['App']['ReasonixSetApprovalMode'](arg1);
}

export function ReasonixSetDefaultModel(arg1) {
  return window['go']['main']['App']['ReasonixSetDefaultModel'](arg1);
}

export function ReasonixSetHomeIsolated(arg1) {
  return window['go']['main']['App']['ReasonixSetHomeIsolated'](arg1);
}

export function ReasonixSetPlannerModel(arg1) {
  return window['go']['main']['App']['ReasonixSetPlannerModel'](arg1);
}

export function ReasonixSettings() {
  return window['go']['main']['App']['ReasonixSettings']();
}

export function ReasonixTestProvider(arg1) {
  return window['go']['main']['App']['ReasonixTestProvider'](arg1);
}

export function ReconnectMCPServer(arg1) {
  return window['go']['main']['App']['ReconnectMCPServer'](arg1);
}

export function RecoverTaskGitWorktree(arg1) {
  return window['go']['main']['App']['RecoverTaskGitWorktree'](arg1);
}

export function RecoveryCheckpointEnabled() {
  return window['go']['main']['App']['RecoveryCheckpointEnabled']();
}

export function RecoveryCheckpointEnabledTab(arg1) {
  return window['go']['main']['App']['RecoveryCheckpointEnabledTab'](arg1);
}

export function RefreshSkills() {
  return window['go']['main']['App']['RefreshSkills']();
}

export function ReloadCommands() {
  return window['go']['main']['App']['ReloadCommands']();
}

export function ReloadSettings() {
  return window['go']['main']['App']['ReloadSettings']();
}

export function Remember(arg1, arg2) {
  return window['go']['main']['App']['Remember'](arg1, arg2);
}

export function RememberForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['RememberForTab'](arg1, arg2, arg3);
}

export function RemoteConnectionStatuses() {
  return window['go']['main']['App']['RemoteConnectionStatuses']();
}

export function RemoteForwards(arg1) {
  return window['go']['main']['App']['RemoteForwards'](arg1);
}

export function RemoteHosts() {
  return window['go']['main']['App']['RemoteHosts']();
}

export function RemoteLastWorkspace(arg1) {
  return window['go']['main']['App']['RemoteLastWorkspace'](arg1);
}

export function RemoteServerLogs(arg1, arg2) {
  return window['go']['main']['App']['RemoteServerLogs'](arg1, arg2);
}

export function RemoteServerStatus(arg1) {
  return window['go']['main']['App']['RemoteServerStatus'](arg1);
}

export function RemoveAgentMessageReference(arg1) {
  return window['go']['main']['App']['RemoveAgentMessageReference'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RemovePermissionRule(arg1, arg2) {
  return window['go']['main']['App']['RemovePermissionRule'](arg1, arg2);
}

export function RemovePlugin(arg1) {
  return window['go']['main']['App']['RemovePlugin'](arg1);
}

export function RemoveProviderAccess(arg1) {
  return window['go']['main']['App']['RemoveProviderAccess'](arg1);
}

export function RemoveRemoteForward(arg1, arg2) {
  return window['go']['main']['App']['RemoveRemoteForward'](arg1, arg2);
}

export function RemoveRemoteHost(arg1) {
  return window['go']['main']['App']['RemoveRemoteHost'](arg1);
}

export function RemoveSkillPath(arg1) {
  return window['go']['main']['App']['RemoveSkillPath'](arg1);
}

export function RemoveWorkspace(arg1) {
  return window['go']['main']['App']['RemoveWorkspace'](arg1);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function RenameRemotePath(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameRemotePath'](arg1, arg2, arg3);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RenameTerminalForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameTerminalForTab'](arg1, arg2, arg3);
}

export function RenameTopic(arg1, arg2) {
  return window['go']['main']['App']['RenameTopic'](arg1, arg2);
}

export function ReorderProjects(arg1) {
  return window['go']['main']['App']['ReorderProjects'](arg1);
}

export function ReorderTabs(arg1) {
  return window['go']['main']['App']['ReorderTabs'](arg1);
}

export function ReplayPendingPrompts() {
  return window['go']['main']['App']['ReplayPendingPrompts']();
}

export function ReportCrash(arg1, arg2) {
  return window['go']['main']['App']['ReportCrash'](arg1, arg2);
}

export function ResetProviderPresetAccess(arg1) {
  return window['go']['main']['App']['ResetProviderPresetAccess'](arg1);
}

export function ResetThemePack() {
  return window['go']['main']['App']['ResetThemePack']();
}

export function ResizeTerminalForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResizeTerminalForTab'](arg1, arg2, arg3, arg4);
}

export function ResolveAgentPermission(arg1) {
  return window['go']['main']['App']['ResolveAgentPermission'](arg1);
}

export function ResolveRecovery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveRecovery'](arg1, arg2, arg3);
}

export function ResolveRecoveryTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResolveRecoveryTab'](arg1, arg2, arg3, arg4);
}

export function RestartApplication() {
  return window['go']['main']['App']['RestartApplication']();
}

export function RestoreArchivedMemory(arg1) {
  return window['go']['main']['App']['RestoreArchivedMemory'](arg1);
}

export function RestoreArchivedMemoryForTab(arg1, arg2) {
  return window['go']['main']['App']['RestoreArchivedMemoryForTab'](arg1, arg2);
}

export function RestoreGraphiteAppearance() {
  return window['go']['main']['App']['RestoreGraphiteAppearance']();
}

export function RestoreMemoryRevision(arg1, arg2) {
  return window['go']['main']['App']['RestoreMemoryRevision'](arg1, arg2);
}

export function RestoreMemoryRevisionForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreMemoryRevisionForTab'](arg1, arg2, arg3);
}

export function RestoreSession(arg1) {
  return window['go']['main']['App']['RestoreSession'](arg1);
}

export function ResumeAgentSession(arg1) {
  return window['go']['main']['App']['ResumeAgentSession'](arg1);
}

export function ResumeGoalForTab(arg1) {
  return window['go']['main']['App']['ResumeGoalForTab'](arg1);
}

export function ResumeSession(arg1) {
  return window['go']['main']['App']['ResumeSession'](arg1);
}

export function ResumeSessionForTab(arg1, arg2) {
  return window['go']['main']['App']['ResumeSessionForTab'](arg1, arg2);
}

export function ResumeSessionPage(arg1, arg2) {
  return window['go']['main']['App']['ResumeSessionPage'](arg1, arg2);
}

export function ResumeSessionPageForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResumeSessionPageForTab'](arg1, arg2, arg3);
}

export function RevealPath(arg1) {
  return window['go']['main']['App']['RevealPath'](arg1);
}

export function RevealWorkspacePath(arg1) {
  return window['go']['main']['App']['RevealWorkspacePath'](arg1);
}

export function RevealWorkspacePathForTab(arg1, arg2) {
  return window['go']['main']['App']['RevealWorkspacePathForTab'](arg1, arg2);
}

export function RevokeAgentPermissionGrant(arg1) {
  return window['go']['main']['App']['RevokeAgentPermissionGrant'](arg1);
}

export function Rewind(arg1, arg2) {
  return window['go']['main']['App']['Rewind'](arg1, arg2);
}

export function RewindForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['RewindForTab'](arg1, arg2, arg3);
}

export function RunShell(arg1) {
  return window['go']['main']['App']['RunShell'](arg1);
}

export function RunShellForTab(arg1, arg2) {
  return window['go']['main']['App']['RunShellForTab'](arg1, arg2);
}

export function SaveClipboardImage() {
  return window['go']['main']['App']['SaveClipboardImage']();
}

export function SaveDailyReportToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDailyReportToken'](arg1, arg2, arg3);
}

export function SaveDoc(arg1, arg2) {
  return window['go']['main']['App']['SaveDoc'](arg1, arg2);
}

export function SaveDocForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDocForTab'](arg1, arg2, arg3);
}

export function SaveExportFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveExportFile'](arg1, arg2, arg3);
}

export function SaveExportImageFiles(arg1, arg2) {
  return window['go']['main']['App']['SaveExportImageFiles'](arg1, arg2);
}

export function SaveHooksSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveHooksSettings'](arg1, arg2);
}

export function SaveHooksSettingsForRoot(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveHooksSettingsForRoot'](arg1, arg2, arg3);
}

export function SavePastedFile(arg1, arg2) {
  return window['go']['main']['App']['SavePastedFile'](arg1, arg2);
}

export function SavePastedImage(arg1) {
  return window['go']['main']['App']['SavePastedImage'](arg1);
}

export function SavePlaneToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePlaneToken'](arg1, arg2, arg3);
}

export function SaveProvider(arg1) {
  return window['go']['main']['App']['SaveProvider'](arg1);
}

export function SaveProviderKey(arg1, arg2) {
  return window['go']['main']['App']['SaveProviderKey'](arg1, arg2);
}

export function SaveProviderWithKey(arg1, arg2) {
  return window['go']['main']['App']['SaveProviderWithKey'](arg1, arg2);
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}

export function SaveThemePack(arg1) {
  return window['go']['main']['App']['SaveThemePack'](arg1);
}

export function SaveWindowState(arg1) {
  return window['go']['main']['App']['SaveWindowState'](arg1);
}

export function ScanPromptHistory(arg1) {
  return window['go']['main']['App']['ScanPromptHistory'](arg1);
}

export function ScanSSHConfig() {
  return window['go']['main']['App']['ScanSSHConfig']();
}

export function SearchFileRefs(arg1) {
  return window['go']['main']['App']['SearchFileRefs'](arg1);
}

export function SearchFileRefsForTab(arg1, arg2) {
  return window['go']['main']['App']['SearchFileRefsForTab'](arg1, arg2);
}

export function SelectDailyReportProjectDirectory() {
  return window['go']['main']['App']['SelectDailyReportProjectDirectory']();
}

export function SelectGitRepository() {
  return window['go']['main']['App']['SelectGitRepository']();
}

export function SelectTaskContextRoot() {
  return window['go']['main']['App']['SelectTaskContextRoot']();
}

export function SendAgentPrompt(arg1) {
  return window['go']['main']['App']['SendAgentPrompt'](arg1);
}

export function SetActiveTab(arg1) {
  return window['go']['main']['App']['SetActiveTab'](arg1);
}

export function SetAgentParams(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAgentParams'](arg1, arg2, arg3, arg4);
}

export function SetAutoApproveTools(arg1) {
  return window['go']['main']['App']['SetAutoApproveTools'](arg1);
}

export function SetAutoPlan(arg1) {
  return window['go']['main']['App']['SetAutoPlan'](arg1);
}

export function SetBotConnectionToolApprovalMode(arg1, arg2) {
  return window['go']['main']['App']['SetBotConnectionToolApprovalMode'](arg1, arg2);
}

export function SetBotSecret(arg1, arg2) {
  return window['go']['main']['App']['SetBotSecret'](arg1, arg2);
}

export function SetBotSettings(arg1) {
  return window['go']['main']['App']['SetBotSettings'](arg1);
}

export function SetBypass(arg1) {
  return window['go']['main']['App']['SetBypass'](arg1);
}

export function SetCloseBehavior(arg1) {
  return window['go']['main']['App']['SetCloseBehavior'](arg1);
}

export function SetColdResumePrune(arg1) {
  return window['go']['main']['App']['SetColdResumePrune'](arg1);
}

export function SetCollaborationMode(arg1) {
  return window['go']['main']['App']['SetCollaborationMode'](arg1);
}

export function SetCollaborationModeForTab(arg1, arg2) {
  return window['go']['main']['App']['SetCollaborationModeForTab'](arg1, arg2);
}

export function SetComposerProfileForTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetComposerProfileForTab'](arg1, arg2, arg3, arg4);
}

export function SetDefaultAutoRecoveryCheckpoint(arg1) {
  return window['go']['main']['App']['SetDefaultAutoRecoveryCheckpoint'](arg1);
}

export function SetDefaultModel(arg1) {
  return window['go']['main']['App']['SetDefaultModel'](arg1);
}

export function SetDefaultToolApprovalMode(arg1) {
  return window['go']['main']['App']['SetDefaultToolApprovalMode'](arg1);
}

export function SetDesktopAppearance(arg1, arg2) {
  return window['go']['main']['App']['SetDesktopAppearance'](arg1, arg2);
}

export function SetDesktopCheckUpdates(arg1) {
  return window['go']['main']['App']['SetDesktopCheckUpdates'](arg1);
}

export function SetDesktopConversationWidth(arg1) {
  return window['go']['main']['App']['SetDesktopConversationWidth'](arg1);
}

export function SetDesktopCurrency(arg1) {
  return window['go']['main']['App']['SetDesktopCurrency'](arg1);
}

export function SetDesktopLanguage(arg1) {
  return window['go']['main']['App']['SetDesktopLanguage'](arg1);
}

export function SetDesktopLayoutStyle(arg1) {
  return window['go']['main']['App']['SetDesktopLayoutStyle'](arg1);
}

export function SetDesktopMetrics(arg1) {
  return window['go']['main']['App']['SetDesktopMetrics'](arg1);
}

export function SetDesktopTelemetry(arg1) {
  return window['go']['main']['App']['SetDesktopTelemetry'](arg1);
}

export function SetDesktopUpdateChannel(arg1) {
  return window['go']['main']['App']['SetDesktopUpdateChannel'](arg1);
}

export function SetDesktopZoomFactor(arg1) {
  return window['go']['main']['App']['SetDesktopZoomFactor'](arg1);
}

export function SetDisplayMode(arg1) {
  return window['go']['main']['App']['SetDisplayMode'](arg1);
}

export function SetEffort(arg1) {
  return window['go']['main']['App']['SetEffort'](arg1);
}

export function SetEffortForTab(arg1, arg2) {
  return window['go']['main']['App']['SetEffortForTab'](arg1, arg2);
}

export function SetExpandThinking(arg1) {
  return window['go']['main']['App']['SetExpandThinking'](arg1);
}

export function SetGoal(arg1) {
  return window['go']['main']['App']['SetGoal'](arg1);
}

export function SetGoalForTab(arg1, arg2) {
  return window['go']['main']['App']['SetGoalForTab'](arg1, arg2);
}

export function SetMCPServerEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetMCPServerEnabled'](arg1, arg2);
}

export function SetMCPServerTier(arg1, arg2) {
  return window['go']['main']['App']['SetMCPServerTier'](arg1, arg2);
}

export function SetMaxParallelWriters(arg1) {
  return window['go']['main']['App']['SetMaxParallelWriters'](arg1);
}

export function SetMaxSubagentConcurrency(arg1) {
  return window['go']['main']['App']['SetMaxSubagentConcurrency'](arg1);
}

export function SetMaxSubagentDepth(arg1) {
  return window['go']['main']['App']['SetMaxSubagentDepth'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function SetModeForTab(arg1, arg2) {
  return window['go']['main']['App']['SetModeForTab'](arg1, arg2);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SetModelForTab(arg1, arg2) {
  return window['go']['main']['App']['SetModelForTab'](arg1, arg2);
}

export function SetNetwork(arg1) {
  return window['go']['main']['App']['SetNetwork'](arg1);
}

export function SetPermissionMode(arg1) {
  return window['go']['main']['App']['SetPermissionMode'](arg1);
}

export function SetPlanMode(arg1) {
  return window['go']['main']['App']['SetPlanMode'](arg1);
}

export function SetPlannerModel(arg1) {
  return window['go']['main']['App']['SetPlannerModel'](arg1);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetPluginEnabled'](arg1, arg2);
}

export function SetPreferredExternalOpener(arg1) {
  return window['go']['main']['App']['SetPreferredExternalOpener'](arg1);
}

export function SetProjectColor(arg1, arg2) {
  return window['go']['main']['App']['SetProjectColor'](arg1, arg2);
}

export function SetProjectPinned(arg1, arg2) {
  return window['go']['main']['App']['SetProjectPinned'](arg1, arg2);
}

export function SetProviderKey(arg1, arg2) {
  return window['go']['main']['App']['SetProviderKey'](arg1, arg2);
}

export function SetReasoningLanguage(arg1) {
  return window['go']['main']['App']['SetReasoningLanguage'](arg1);
}

export function SetRecoveryCheckpointEnabled(arg1) {
  return window['go']['main']['App']['SetRecoveryCheckpointEnabled'](arg1);
}

export function SetRecoveryCheckpointEnabledTab(arg1, arg2) {
  return window['go']['main']['App']['SetRecoveryCheckpointEnabledTab'](arg1, arg2);
}

export function SetSandbox(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetSandbox'](arg1, arg2, arg3, arg4, arg5);
}

export function SetSkillEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetSkillEnabled'](arg1, arg2);
}

export function SetStatusBarItems(arg1) {
  return window['go']['main']['App']['SetStatusBarItems'](arg1);
}

export function SetStatusBarStyle(arg1) {
  return window['go']['main']['App']['SetStatusBarStyle'](arg1);
}

export function SetSubagentEffort(arg1) {
  return window['go']['main']['App']['SetSubagentEffort'](arg1);
}

export function SetSubagentModel(arg1) {
  return window['go']['main']['App']['SetSubagentModel'](arg1);
}

export function SetSubagentProfileEffort(arg1, arg2) {
  return window['go']['main']['App']['SetSubagentProfileEffort'](arg1, arg2);
}

export function SetSubagentProfileModel(arg1, arg2) {
  return window['go']['main']['App']['SetSubagentProfileModel'](arg1, arg2);
}

export function SetTaskContextRoot(arg1) {
  return window['go']['main']['App']['SetTaskContextRoot'](arg1);
}

export function SetTokenMode(arg1) {
  return window['go']['main']['App']['SetTokenMode'](arg1);
}

export function SetTokenModeForTab(arg1, arg2) {
  return window['go']['main']['App']['SetTokenModeForTab'](arg1, arg2);
}

export function SetToolApprovalMode(arg1) {
  return window['go']['main']['App']['SetToolApprovalMode'](arg1);
}

export function SetToolApprovalModeForTab(arg1, arg2) {
  return window['go']['main']['App']['SetToolApprovalModeForTab'](arg1, arg2);
}

export function SetTopicPinned(arg1, arg2) {
  return window['go']['main']['App']['SetTopicPinned'](arg1, arg2);
}

export function SetTrayLocale(arg1) {
  return window['go']['main']['App']['SetTrayLocale'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function SetupPlaneConnection(arg1, arg2) {
  return window['go']['main']['App']['SetupPlaneConnection'](arg1, arg2);
}

export function SkillsSettings() {
  return window['go']['main']['App']['SkillsSettings']();
}

export function SlashArgs(arg1) {
  return window['go']['main']['App']['SlashArgs'](arg1);
}

export function StartBotConnectionInstall(arg1, arg2) {
  return window['go']['main']['App']['StartBotConnectionInstall'](arg1, arg2);
}

export function Steer(arg1) {
  return window['go']['main']['App']['Steer'](arg1);
}

export function SteerAgent(arg1) {
  return window['go']['main']['App']['SteerAgent'](arg1);
}

export function SteerForTab(arg1, arg2) {
  return window['go']['main']['App']['SteerForTab'](arg1, arg2);
}

export function StopAgentToolExecution(arg1) {
  return window['go']['main']['App']['StopAgentToolExecution'](arg1);
}

export function StopRemoteServer(arg1) {
  return window['go']['main']['App']['StopRemoteServer'](arg1);
}

export function Submit(arg1) {
  return window['go']['main']['App']['Submit'](arg1);
}

export function SubmitDailyReport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubmitDailyReport'](arg1, arg2, arg3, arg4);
}

export function SubmitDeliveryRecoveryToTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitDeliveryRecoveryToTab'](arg1, arg2, arg3);
}

export function SubmitDisplay(arg1, arg2) {
  return window['go']['main']['App']['SubmitDisplay'](arg1, arg2);
}

export function SubmitDisplayToTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitDisplayToTab'](arg1, arg2, arg3);
}

export function SubmitEditedDisplayToTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubmitEditedDisplayToTab'](arg1, arg2, arg3, arg4);
}

export function SubmitInitialGoalToTab(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['SubmitInitialGoalToTab'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SubmitInvocationsToTab(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubmitInvocationsToTab'](arg1, arg2, arg3, arg4);
}

export function SubmitToTab(arg1, arg2) {
  return window['go']['main']['App']['SubmitToTab'](arg1, arg2);
}

export function SummarizeFrom(arg1) {
  return window['go']['main']['App']['SummarizeFrom'](arg1);
}

export function SummarizeFromForTab(arg1, arg2) {
  return window['go']['main']['App']['SummarizeFromForTab'](arg1, arg2);
}

export function SummarizeUpTo(arg1) {
  return window['go']['main']['App']['SummarizeUpTo'](arg1);
}

export function SummarizeUpToForTab(arg1, arg2) {
  return window['go']['main']['App']['SummarizeUpToForTab'](arg1, arg2);
}

export function SwitchWorkspace(arg1) {
  return window['go']['main']['App']['SwitchWorkspace'](arg1);
}

export function TerminalOutputForTab(arg1, arg2) {
  return window['go']['main']['App']['TerminalOutputForTab'](arg1, arg2);
}

export function TerminalWorkspaceForTab(arg1) {
  return window['go']['main']['App']['TerminalWorkspaceForTab'](arg1);
}

export function TestBotConnection(arg1, arg2) {
  return window['go']['main']['App']['TestBotConnection'](arg1, arg2);
}

export function TestPlaneConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestPlaneConnection'](arg1, arg2, arg3);
}

export function ToggleMaximiseMainWindow() {
  return window['go']['main']['App']['ToggleMaximiseMainWindow']();
}

export function ToolResultForTab(arg1, arg2) {
  return window['go']['main']['App']['ToolResultForTab'](arg1, arg2);
}

export function TrashTopic(arg1) {
  return window['go']['main']['App']['TrashTopic'](arg1);
}

export function TrustProjectHooks() {
  return window['go']['main']['App']['TrustProjectHooks']();
}

export function TrustProjectHooksForRoot(arg1) {
  return window['go']['main']['App']['TrustProjectHooksForRoot'](arg1);
}

export function TrySubagentProfile(arg1, arg2) {
  return window['go']['main']['App']['TrySubagentProfile'](arg1, arg2);
}

export function UpdateMCPServer(arg1, arg2) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1, arg2);
}

export function UpdatePlugin(arg1) {
  return window['go']['main']['App']['UpdatePlugin'](arg1);
}

export function UpdateRemoteHost(arg1, arg2) {
  return window['go']['main']['App']['UpdateRemoteHost'](arg1, arg2);
}

export function UpdateSubagentProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSubagentProfile'](arg1, arg2, arg3);
}

export function ValidateTransition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ValidateTransition'](arg1, arg2, arg3, arg4, arg5);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WorkbenchActiveTarget() {
  return window['go']['main']['App']['WorkbenchActiveTarget']();
}

export function WorkbenchConnectRemote(arg1, arg2) {
  return window['go']['main']['App']['WorkbenchConnectRemote'](arg1, arg2);
}

export function WorkbenchDisconnectRemote() {
  return window['go']['main']['App']['WorkbenchDisconnectRemote']();
}

export function WorkbenchLastRemoteHint() {
  return window['go']['main']['App']['WorkbenchLastRemoteHint']();
}

export function WorkbenchPendingProviderTrust() {
  return window['go']['main']['App']['WorkbenchPendingProviderTrust']();
}

export function WorkbenchRemoteRequest(arg1, arg2) {
  return window['go']['main']['App']['WorkbenchRemoteRequest'](arg1, arg2);
}

export function WorkbenchResolveProviderTrust(arg1) {
  return window['go']['main']['App']['WorkbenchResolveProviderTrust'](arg1);
}

export function WorkbenchSwitchLocal() {
  return window['go']['main']['App']['WorkbenchSwitchLocal']();
}

export function WorkspaceChangeDetail(arg1, arg2) {
  return window['go']['main']['App']['WorkspaceChangeDetail'](arg1, arg2);
}

export function WorkspaceChanges(arg1) {
  return window['go']['main']['App']['WorkspaceChanges'](arg1);
}

export function WorkspaceGitCommitDetail(arg1, arg2, arg3) {
  return window['go']['main']['App']['WorkspaceGitCommitDetail'](arg1, arg2, arg3);
}

export function WorkspaceGitHistory(arg1, arg2) {
  return window['go']['main']['App']['WorkspaceGitHistory'](arg1, arg2);
}

export function WriteRemoteFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteRemoteFile'](arg1, arg2, arg3, arg4);
}

export function WriteTerminalForTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteTerminalForTab'](arg1, arg2, arg3);
}
